--[[
	IconLibrary -- the asset layer the HUD never had (ROADMAP 9.9).

	Before this, every icon in the game was an EMOJI IN A TEXTLABEL. A tree scan found zero
	ImageLabels and zero rbxassetid strings in the whole interface. That is not a style choice, it
	is a different picture on every platform: Windows, Android, iOS and console each ship their own
	emoji font, so the same tile renders four ways and not one of them shares the thick dark
	outline and flat pastel fill that every other surface in this game is built from.

	The art is generated by `tools/make_icons.py` and uploaded once; `assets/icons/uploaded.json`
	is the record of that upload and this table is what the game reads. Regenerating a PNG does not
	change its asset id -- if the art moves, it has to be uploaded again and the id replaced here.

	===== THE ONE RULE THAT MATTERS: LOOKUP IS BY EMOJI =====

	`BY_EMOJI` maps the emoji a call site ALREADY passes to an icon. Nothing else was possible at a
	sane cost: emojis are written in `GameConfig` rows (twenty stages, a hundred pet species, nine
	passes, seventeen products, thirty season rewards), in `MainUI`, and in payloads the server
	sends the client. Threading an `iconKey` field through all of those would be a hundred edits
	and every one of them a chance to miss a row.

	So a call site keeps saying "\u{1F9EC}" and gets a drawn double helix. The emoji stays in the
	source as what it always was -- a legible name for the thing -- and becomes the KEY as well.

	===== AND WHY AN UNMAPPED EMOJI IS NOT A BUG =====

	`Resolve` returns nil for anything it does not know, and every call site draws the emoji when it
	does. That is the whole fallback, and it is what makes this safe to ship half-finished:

	  * 128 distinct emojis exist across the client and GameConfig, and ~90 of them are SPECIES
	    IDENTITY -- a Swarmer is a bug, a pet is a fox. Those are not interface chrome and they are
	    not worth 90 more uploads; they are also the ones where the platform emoji is genuinely
	    good, because it is a picture of an animal drawn by a type foundry.
	  * A new emoji added to GameConfig next year renders exactly as it does today until somebody
	    adds a row here. It can never render as nothing, which is the failure mode an asset layer
	    normally introduces (see the SoundLibrary header: a moderated asset is not an error, it is
	    silence -- and here it would be an empty square).

	Same reason `Has` exists rather than call sites comparing against nil themselves.
]]

local IconLibrary = {}

-- ===== THE ASSETS =====
-- Names match `tools/make_icons.py` and `assets/icons/uploaded.json` exactly. Do not rename one
-- without the other two.
local ID = {
	dna       = "rbxassetid://81434690219399",
	diamond   = "rbxassetid://130283776476870",
	shard     = "rbxassetid://109021070436279",
	xp        = "rbxassetid://107775900051043",
	luck      = "rbxassetid://121532874219481",
	sword     = "rbxassetid://104391890869412",
	paw       = "rbxassetid://76239497429653",
	potion    = "rbxassetid://99999317917015",
	egg       = "rbxassetid://107032143247002",
	crown     = "rbxassetid://76791476727334",
	lock      = "rbxassetid://101615815229927",
	check     = "rbxassetid://94096354033963",
	cross     = "rbxassetid://126922218599181",
	fire      = "rbxassetid://118575692998570",
	clock     = "rbxassetid://140329280761162",
	wheel     = "rbxassetid://97712433514837",
	upgrade   = "rbxassetid://131840105948434",
	arrow     = "rbxassetid://138420523300304",
	question  = "rbxassetid://114563777659487",
	boom      = "rbxassetid://131337550097639",
	coin      = "rbxassetid://129513347169030",
	gear      = "rbxassetid://120219310542767",
	bolt      = "rbxassetid://100617901114870",
	ticket    = "rbxassetid://112939594103107",
	gift      = "rbxassetid://83944471849827",
	cart      = "rbxassetid://138827402391986",
	bag       = "rbxassetid://74045941803440",
	book      = "rbxassetid://75156244958882",
	map       = "rbxassetid://89873662284176",
	rebirth   = "rbxassetid://77260142925404",
	backpack  = "rbxassetid://91824526387988",
	audio     = "rbxassetid://89347950978095",
	medal     = "rbxassetid://121983672866560",
	rainbow   = "rbxassetid://89084335349565",
	sun       = "rbxassetid://121798912637171",
	calendar  = "rbxassetid://76380530027551",
	party     = "rbxassetid://87717541564323",
	hourglass = "rbxassetid://128862957992094",
	boss      = "rbxassetid://130454681228865",
	heart     = "rbxassetid://77811537280917",
	plus      = "rbxassetid://93901047663431",
	shop      = "rbxassetid://132821656068720",
	zone      = "rbxassetid://111515559788213",
	pet       = "rbxassetid://81488146657952",
}
IconLibrary.Id = ID

-- ===== EMOJI -> ICON =====
--
-- Several emojis deliberately share an icon. That is not laziness: ⏰ ⏳ ⌛ ⏱️ are four drawings of
-- one idea ("time"), and a set where every near-synonym gets its own subtly different clock is
-- harder to read at 40 px than one where they all get the same one. The exception is where the
-- game gives two of them DIFFERENT MEANINGS -- ⭐ is Evolution XP and 🌟 is an Evolution Shard, and
-- those two sit next to each other on the Daily panel, so they are a five-point star and a
-- four-point sparkle and must never be merged.
local BY_EMOJI = {
	-- currencies and stats
	["\u{1F9EC}"] = "dna",       -- 🧬
	["\u{1F48E}"] = "diamond",   -- 💎
	["\u{1F31F}"] = "shard",     -- 🌟  (Evolution Shard -- NOT the same as ⭐)
	["\u{2B50}"]  = "xp",        -- ⭐  (Evolution XP)
	["\u{1F340}"] = "luck",      -- 🍀
	["\u{1F4B0}"] = "coin",      -- 💰
	["\u{2694}\u{FE0F}"] = "sword",   -- ⚔️
	["\u{2694}"]  = "sword",          -- the same emoji written without its variation selector
	["\u{1F4A5}"] = "boom",      -- 💥
	["\u{2764}\u{FE0F}"] = "heart",   -- ❤️
	["\u{1F49C}"] = "heart",     -- 💜

	-- inventory and shops
	["\u{1F6D2}"] = "cart",      -- 🛒
	["\u{1F6CD}\u{FE0F}"] = "bag",    -- 🛍️
	["\u{1F6CD}"] = "bag",
	["\u{1F3EA}"] = "shop",      -- 🏪
	["\u{1F392}"] = "backpack",  -- 🎒
	["\u{1F9EA}"] = "potion",    -- 🧪
	["\u{2697}\u{FE0F}"] = "potion",  -- ⚗️
	["\u{2697}"]  = "potion",
	["\u{1F95A}"] = "egg",       -- 🥚
	["\u{1F423}"] = "egg",       -- 🐣
	["\u{1F43E}"] = "paw",       -- 🐾

	-- navigation and screens
	["\u{1F4D2}"] = "book",      -- 📒
	["\u{1F4D6}"] = "book",      -- 📖
	["\u{1F5FA}\u{FE0F}"] = "map",    -- 🗺️
	["\u{1F5FA}"] = "map",
	["\u{267B}\u{FE0F}"] = "rebirth", -- ♻️
	["\u{267B}"]  = "rebirth",
	["\u{1F50A}"] = "audio",     -- 🔊
	["\u{1F3A1}"] = "wheel",     -- 🎡
	["\u{1F39F}\u{FE0F}"] = "ticket", -- 🎟️
	["\u{1F39F}"] = "ticket",
	["\u{1F381}"] = "gift",      -- 🎁
	["\u{1F4C5}"] = "calendar",  -- 📅
	["\u{1F389}"] = "party",     -- 🎉

	-- state and feedback
	["\u{1F512}"] = "lock",      -- 🔒
	["\u{2713}"]  = "check",     -- ✓
	["\u{2714}\u{FE0F}"] = "check",   -- ✔️
	["\u{274C}"]  = "cross",     -- ❌
	["\u{2753}"]  = "question",  -- ❓
	["\u{2757}"]  = "question",  -- ❗
	["\u{2B06}\u{FE0F}"] = "upgrade", -- ⬆️
	["\u{2B06}"]  = "upgrade",
	["\u{27A1}\u{FE0F}"] = "arrow",   -- ➡️
	["\u{27A1}"]  = "arrow",
	["\u{2192}"]  = "arrow",     -- →
	["\u{2795}"]  = "plus",      -- ➕
	["\u{1F525}"] = "fire",      -- 🔥
	["\u{26A1}"]  = "bolt",      -- ⚡
	["\u{2699}\u{FE0F}"] = "gear",    -- ⚙️
	["\u{2699}"]  = "gear",
	["\u{1F308}"] = "rainbow",   -- 🌈
	["\u{2600}\u{FE0F}"] = "sun",     -- ☀️
	["\u{2600}"]  = "sun",
	["\u{1F451}"] = "crown",     -- 👑
	["\u{1F3C5}"] = "medal",     -- 🏅
	["\u{1F947}"] = "medal",     -- 🥇
	["\u{1F479}"] = "boss",      -- 👹
	["\u{1F408}"] = "pet",       -- 🐈
	["\u{1F431}"] = "pet",       -- 🐱

	-- TIME. Four emojis, one idea, one drawing -- see the note above this table.
	["\u{23F0}"] = "clock",      -- ⏰
	["\u{23F3}"] = "hourglass",  -- ⏳
	["\u{231B}"] = "hourglass",  -- ⌛
	["\u{23F1}\u{FE0F}"] = "clock",   -- ⏱️
	["\u{23F1}"] = "clock",
}

-- Returns the asset id for an emoji, or nil when there is no icon for it -- which is a normal
-- answer, not a failure. See the header.
function IconLibrary.Resolve(emoji)
	if type(emoji) ~= "string" or emoji == "" then return nil end
	local key = BY_EMOJI[emoji]
	if key then return ID[key] end
	-- A call site may pass "🧬 DNA" rather than a bare glyph -- the Button and Card helpers
	-- concatenate an icon onto its text. Matching the leading glyph costs one substring compare per
	-- distinct length, and the alternative is every caller learning to split its own string.
	--
	-- Descending, so that "⚔️" (two code points, 6 bytes with the variation selector) is tried
	-- before "⚔" (3 bytes) -- otherwise the shorter prefix always wins and the selector is left
	-- dangling on the front of the remaining text.
	for _, n in ipairs({ 8, 7, 6, 4, 3 }) do
		local head = emoji:sub(1, n)
		local hit = BY_EMOJI[head]
		if hit then return ID[hit] end
	end
	return nil
end

function IconLibrary.Has(emoji)
	return IconLibrary.Resolve(emoji) ~= nil
end

-- Strips a leading mapped emoji (and the space after it) off a label, so a caption that reads
-- "🧬 DNA" becomes "DNA" once the glyph has been replaced by a drawn icon beside it. Returns the
-- string untouched when nothing was stripped, so it is safe to call on anything.
function IconLibrary.StripLeading(text)
	if type(text) ~= "string" then return text end
	for _, n in ipairs({ 8, 7, 6, 4, 3 }) do
		if BY_EMOJI[text:sub(1, n)] then
			-- one optional space, not `%s*`: a caption is allowed to start with an indent and eating
			-- it would silently reflow the label
			local rest = text:sub(n + 1)
			return (rest:sub(1, 1) == " ") and rest:sub(2) or rest
		end
	end
	return text
end

return IconLibrary
