--[[
	IconLibrary -- the asset layer the HUD never had (ROADMAP 9.9).

	Before this, every icon in the game was an EMOJI IN A TEXTLABEL. A tree scan found zero
	ImageLabels and zero rbxassetid strings in the whole interface. That is not a style choice, it
	is a different picture on every platform: Windows, Android, iOS and console each ship their own
	emoji font, so the same tile renders four ways and not one of them shares the thick dark
	outline and flat pastel fill that every other surface in this game is built from.

	The art is generated by `tools/make_icons.py` and uploaded once; `assets/icons/uploaded.json`
	is the record of that upload and this table is what the game reads. Regenerating a PNG does not
	change its asset id -- if the art moves, it has to be uploaded again and the id replaced here.

	===== THE ONE RULE THAT MATTERS: LOOKUP IS BY EMOJI =====

	`BY_EMOJI` maps the emoji a call site ALREADY passes to an icon. Nothing else was possible at a
	sane cost: emojis are written in `GameConfig` rows (twenty stages, a hundred pet species, nine
	passes, seventeen products, thirty season rewards), in `MainUI`, and in payloads the server
	sends the client. Threading an `iconKey` field through all of those would be a hundred edits
	and every one of them a chance to miss a row.

	So a call site keeps saying "\u{1F9EC}" and gets a drawn double helix. The emoji stays in the
	source as what it always was -- a legible name for the thing -- and becomes the KEY as well.

	===== AND WHY AN UNMAPPED EMOJI IS NOT A BUG =====

	`Resolve` returns nil for anything it does not know, and every call site draws the emoji when it
	does. That is the whole fallback, and it is what makes this safe to ship half-finished:

	  * 128 distinct emojis exist across the client and GameConfig, and ~90 of them are SPECIES
	    IDENTITY -- a Swarmer is a bug, a pet is a fox. Those are not interface chrome and they are
	    not worth 90 more uploads; they are also the ones where the platform emoji is genuinely
	    good, because it is a picture of an animal drawn by a type foundry.
	  * A new emoji added to GameConfig next year renders exactly as it does today until somebody
	    adds a row here. It can never render as nothing, which is the failure mode an asset layer
	    normally introduces (see the SoundLibrary header: a moderated asset is not an error, it is
	    silence -- and here it would be an empty square).

	Same reason `Has` exists rather than call sites comparing against nil themselves.
]]

local IconLibrary = {}

-- ===== THE ASSETS =====
-- Names match `tools/make_icons.py` and `assets/icons/uploaded.json` exactly. Do not rename one
-- without the other two.
local ID = {
	absolute     = "rbxassetid://133654512361485",
	arrow        = "rbxassetid://100683138086656",
	audio        = "rbxassetid://77987918035205",
	backpack     = "rbxassetid://112267210821022",
	bag          = "rbxassetid://12600727274",
	blackhole    = "rbxassetid://86622214176705",
	bolt         = "rbxassetid://125449019286643",
	book         = "rbxassetid://75827505162710",
	boom         = "rbxassetid://98622443720558",
	boss         = "rbxassetid://75913353547225",
	calendar     = "rbxassetid://114216417880572",
	cart         = "rbxassetid://120268752774798",
	check        = "rbxassetid://139079900516571",
	clock        = "rbxassetid://110502368703038",
	coin         = "rbxassetid://138155477964656",
	cross        = "rbxassetid://79209920954791",
	crown        = "rbxassetid://100737784411045",
	desert       = "rbxassetid://107579072515574",
	diamond      = "rbxassetid://94306408327096",
	dna          = "rbxassetid://97605056516888",
	dream        = "rbxassetid://84498845488665",
	egg          = "rbxassetid://85200417748395",
	fire         = "rbxassetid://114362288516361",
	forest       = "rbxassetid://139549052766790",
	galaxy       = "rbxassetid://73608735294271",
	gear         = "rbxassetid://134940823652825",
	gift         = "rbxassetid://116511141331182",
	handshake    = "rbxassetid://105809271165337",
	heart        = "rbxassetid://103783313754607",
	home         = "rbxassetid://117910760992150",
	honey        = "rbxassetid://114133034277624",
	hourglass    = "rbxassetid://136044741795897",
	lock         = "rbxassetid://128372983391438",
	luck         = "rbxassetid://140260937065697",
	map          = "rbxassetid://106964707289711",
	mars         = "rbxassetid://76391200725920",
	medal        = "rbxassetid://79294732633106",
	medal_bronze = "rbxassetid://116258111831735",
	medal_silver = "rbxassetid://126119579368347",
	mirror       = "rbxassetid://112502828175923",
	moon         = "rbxassetid://99231498307217",
	multiverse   = "rbxassetid://86591318170427",
	nebula       = "rbxassetid://102108182273845",
	ocean        = "rbxassetid://73127498026523",
	orb          = "rbxassetid://96092681500201",
	party        = "rbxassetid://123272919810963",
	paw          = "rbxassetid://115889303279770",
	pet          = "rbxassetid://75752760135035",
	plus         = "rbxassetid://91152374913942",
	potion       = "rbxassetid://86593763008335",
	quantum      = "rbxassetid://100109299598613",
	question     = "rbxassetid://84165149952604",
	rainbow      = "rbxassetid://72918578421395",
	rebirth      = "rbxassetid://137919423177940",
	shard        = "rbxassetid://93975864077659",
	shop         = "rbxassetid://79110444339140",
	singularity  = "rbxassetid://76125474367091",
	skull        = "rbxassetid://124856616676295",
	sleep        = "rbxassetid://126193952793647",
	snow         = "rbxassetid://105381723604694",
	sparkle      = "rbxassetid://79993776154604",
	speed        = "rbxassetid://83909543865551",
	sprig        = "rbxassetid://137694586619038",
	sun          = "rbxassetid://128063910082223",
	sword        = "rbxassetid://77111451475226",
	ticket       = "rbxassetid://102723710825138",
	upgrade      = "rbxassetid://94822131391656",
	void         = "rbxassetid://86778432912380",
	volcano      = "rbxassetid://116235909195170",
	warning      = "rbxassetid://98782266115018",
	wheel        = "rbxassetid://136196933572720",
	wormhole     = "rbxassetid://83004249894908",
	xp           = "rbxassetid://90055084700953",
	zone         = "rbxassetid://77905538933584",
}
IconLibrary.Id = ID

-- ===== EMOJI -> ICON =====
--
-- Several emojis deliberately share an icon. That is not laziness: â° â³ âŒ› â±ï¸ are four drawings of
-- one idea ("time"), and a set where every near-synonym gets its own subtly different clock is
-- harder to read at 40 px than one where they all get the same one. The exception is where the
-- game gives two of them DIFFERENT MEANINGS -- â­ is Evolution XP and ðŸŒŸ is an Evolution Shard, and
-- those two sit next to each other on the Daily panel, so they are a five-point star and a
-- four-point sparkle and must never be merged.
local BY_EMOJI = {
	-- currencies and stats
	["\u{1F9EC}"] = "dna",       -- ðŸ§¬
	["\u{1F48E}"] = "diamond",   -- ðŸ’Ž
	["\u{1F31F}"] = "shard",     -- ðŸŒŸ  (Evolution Shard -- NOT the same as â­)
	["\u{2B50}"]  = "xp",        -- â­  (Evolution XP)
	["\u{1F340}"] = "luck",      -- ðŸ€
	["\u{1F4B0}"] = "coin",      -- ðŸ’°
	["\u{2694}\u{FE0F}"] = "sword",   -- âš”ï¸
	["\u{2694}"]  = "sword",          -- the same emoji written without its variation selector
	["\u{1F4A5}"] = "boom",      -- ðŸ’¥
	["\u{2764}\u{FE0F}"] = "heart",   -- â¤ï¸
	["\u{1F49C}"] = "heart",     -- ðŸ’œ

	-- inventory and shops
	["\u{1F6D2}"] = "cart",      -- ðŸ›’
	["\u{1F6CD}\u{FE0F}"] = "bag",    -- ðŸ›ï¸
	["\u{1F6CD}"] = "bag",
	["\u{1F3EA}"] = "shop",      -- ðŸª
	["\u{1F392}"] = "backpack",  -- ðŸŽ’
	["\u{1F9EA}"] = "potion",    -- ðŸ§ª
	["\u{2697}\u{FE0F}"] = "potion",  -- âš—ï¸
	["\u{2697}"]  = "potion",
	["\u{1F95A}"] = "egg",       -- ðŸ¥š
	["\u{1F423}"] = "egg",       -- ðŸ£
	["\u{1F43E}"] = "paw",       -- ðŸ¾

	-- navigation and screens
	["\u{1F4D2}"] = "book",      -- ðŸ“’
	["\u{1F4D6}"] = "book",      -- ðŸ“–
	["\u{1F5FA}\u{FE0F}"] = "zone",    -- ðŸ—ºï¸
	["\u{1F5FA}"] = "zone",
	["\u{267B}\u{FE0F}"] = "rebirth", -- â™»ï¸
	["\u{267B}"]  = "rebirth",
	["\u{1F50A}"] = "audio",     -- ðŸ”Š
	["\u{1F3A1}"] = "wheel",     -- ðŸŽ¡
	["\u{1F39F}\u{FE0F}"] = "ticket", -- ðŸŽŸï¸
	["\u{1F39F}"] = "ticket",
	["\u{1F381}"] = "gift",      -- ðŸŽ
	["\u{1F4C5}"] = "calendar",  -- ðŸ“…
	["\u{1F389}"] = "party",     -- ðŸŽ‰

	-- state and feedback
	["\u{1F512}"] = "lock",      -- ðŸ”’
	["\u{2713}"]  = "check",     -- âœ“
	["\u{2714}\u{FE0F}"] = "check",   -- âœ”ï¸
	["\u{274C}"]  = "cross",     -- âŒ
	["\u{2753}"]  = "question",  -- â“
	["\u{2757}"]  = "question",  -- â—
	["\u{2B06}\u{FE0F}"] = "upgrade", -- â¬†ï¸
	["\u{2B06}"]  = "upgrade",
	["\u{27A1}\u{FE0F}"] = "arrow",   -- âž¡ï¸
	["\u{27A1}"]  = "arrow",
	["\u{2192}"]  = "arrow",     -- â†’
	["\u{2795}"]  = "plus",      -- âž•
	["\u{1F525}"] = "fire",      -- ðŸ”¥
	["\u{26A1}"]  = "bolt",      -- âš¡
	["\u{2699}\u{FE0F}"] = "gear",    -- âš™ï¸
	["\u{2699}"]  = "gear",
	["\u{1F308}"] = "rainbow",   -- ðŸŒˆ
	["\u{2600}\u{FE0F}"] = "sun",     -- â˜€ï¸
	["\u{2600}"]  = "sun",
	["\u{1F451}"] = "crown",     -- ðŸ‘‘
	["\u{1F3C5}"] = "medal",     -- ðŸ…
	["\u{1F947}"] = "medal",     -- ðŸ¥‡
	["\u{1F479}"] = "boss",      -- ðŸ‘¹
	["\u{1F408}"] = "pet",       -- ðŸˆ
	["\u{1F431}"] = "pet",       -- ðŸ±

	-- TIME. Four emojis, one idea, one drawing -- see the note above this table.
	["\u{23F0}"] = "clock",      -- â°
	["\u{23F3}"] = "hourglass",  -- â³
	["\u{231B}"] = "hourglass",  -- âŒ›
	["\u{23F1}\u{FE0F}"] = "clock",   -- â±ï¸
	["\u{23F1}"] = "clock",

	-- ========================================================================
	-- THE ZONES (10.20)
	-- ========================================================================
	-- Seventeen of the twenty zones had no art and fell back to a platform glyph. These are the
	-- BIGGEST icons in the game and it is easy to miss why: the same drawing is used on the zone
	-- row, on the unlock toast, on the boss bar -- and on `ZoneTransition`'s full-screen card,
	-- where it renders at 190x190. Everything else here is read at forty pixels.
	--
	-- THE BOSS ROWS ARE THE SAME EMOJI ON PURPOSE. `GameConfig.ZoneBosses` reuses each zone's glyph
	-- for that zone's boss from Volcano onward, so one drawing lights both places with no extra row
	-- here and nothing to keep in step.
	["\u{1F332}"] = "forest",      -- ðŸŒ² Forest
	["\u{1F3DC}\u{FE0F}"] = "desert",   -- ðŸœï¸ Desert
	["\u{1F3DC}"] = "desert",
	["\u{1F30A}"] = "ocean",       -- ðŸŒŠ Ocean (and the "Deep Currents" season)
	["\u{1F30B}"] = "volcano",     -- ðŸŒ‹ Volcano (and "Ashfall")
	["\u{1F319}"] = "moon",        -- ðŸŒ™ Moon
	["\u{1F534}"] = "mars",        -- ðŸ”´ Mars
	["\u{1F30C}"] = "galaxy",      -- ðŸŒŒ Galaxy
	["\u{26AB}"]  = "blackhole",   -- âš« Black Hole
	["\u{1F300}"] = "multiverse",  -- ðŸŒ€ Multiverse
	["\u{1F320}"] = "nebula",      -- ðŸŒ  Nebula (and "Starfall")
	["\u{1F573}\u{FE0F}"] = "wormhole", -- ðŸ•³ï¸ Wormhole
	["\u{1F573}"] = "wormhole",
	["\u{269B}\u{FE0F}"] = "quantum",   -- âš›ï¸ Quantum Realm
	["\u{269B}"]  = "quantum",
	["\u{1F4AD}"] = "dream",       -- ðŸ’­ Dream Dimension
	["\u{1FA9E}"] = "mirror",      -- ðŸªž Mirror Universe
	["\u{1F311}"] = "void",        -- ðŸŒ‘ Void Expanse
	["\u{1F4AB}"] = "singularity", -- ðŸ’« Singularity
	["\u{1F53A}"] = "absolute",    -- ðŸ”º The Absolute Plane

	-- ========================================================================
	-- CHROME THAT WAS STILL FALLING BACK TO A GLYPH (10.20)
	-- ========================================================================
	-- Found by auditing every emoji that reaches a tile, a pill or a header against this table.
	-- Several are NEAR-MISSES of rows that already existed -- a second tick glyph, a bare âœ” with no
	-- variation selector, a dagger where the rest of the game uses crossed swords -- and those cost
	-- a row each and no art at all. They are grouped with the icon they join.
	["\u{2705}"]  = "check",     -- âœ… the Claimed / Done / Premium-unlocked marks
	["\u{2714}"]  = "check",     -- âœ”  bare, no variation selector: the pet Equipped tick
	["\u{2715}"]  = "cross",     -- âœ•  the pet Release button
	["\u{1F5E1}\u{FE0F}"] = "sword",  -- ðŸ—¡ï¸ the pet card's Damage stat
	["\u{1F5E1}"] = "sword",
	["\u{1F4CB}"] = "book",      -- ðŸ“‹ the Season panel's Quests tab
	["\u{1F948}"] = "medal_silver",   -- ðŸ¥ˆ leaderboard 2nd
	["\u{1F949}"] = "medal_bronze",   -- ðŸ¥‰ leaderboard 3rd
	-- âš  and its selector-less twin: the caution line under the pet Fuse row
	["\u{26A0}\u{FE0F}"] = "warning",
	["\u{26A0}"]  = "warning",
	["\u{1F4A4}"] = "sleep",     -- ðŸ’¤ the offline-earnings card
	["\u{2620}\u{FE0F}"] = "skull",   -- â˜ ï¸ the boss-revive prompt
	["\u{2620}"]  = "skull",
	["\u{2728}"]  = "sparkle",   -- âœ¨ the season track's shard face, and "NEW FORM"
	["\u{1F52E}"] = "orb",       -- ðŸ”® the Mystery Potions shop
	["\u{1F91D}"] = "handshake", -- ðŸ¤ "Trade complete!"
	["\u{1F3E0}"] = "home",      -- ðŸ  the arena's Back portal
	["\u{2744}\u{FE0F}"] = "snow",    -- â„ï¸ the "Frostbloom" season
	["\u{2744}"]  = "snow",
	["\u{1F33F}"] = "sprig",     -- ðŸŒ¿ the "Overgrowth" season
	["\u{1F36F}"] = "honey",     -- ðŸ¯ the Large potion size
	-- SPEED IS ONE DRAWING FOR TWO GLYPHS, and they are the same idea told twice: ðŸ‘Ÿ is the Speed
	-- UPGRADE tile and ðŸƒ is the 2x Speed PASS chip. Before this, the pass chip was the one chip in
	-- a grid of nine that kept a glyph while its neighbours had art.
	["\u{1F45F}"] = "speed",     -- ðŸ‘Ÿ
	["\u{1F3C3}"] = "speed",     -- ðŸƒ

	-- `zone` IS DELIBERATELY LEFT WITH NO EMOJI, and it is the one entry in `ID` that has none.
	-- It was orphaned by accident before 10.20 -- drawn, uploaded and unreachable, which is the
	-- failure `tools/apply_uploads.py` now audits for -- and it stays unmapped on purpose now that
	-- all twenty zones have their own art: a generic green landscape would only ever be shown
	-- INSTEAD of the specific zone, which is worse than the emoji fallback. Kept rather than
	-- deleted because it costs one line and is the obvious drawing for any future "somewhere in
	-- the world" label.
}

-- Returns the asset id for an emoji, or nil when there is no icon for it -- which is a normal
-- answer, not a failure. See the header.
function IconLibrary.Resolve(emoji)
	if type(emoji) ~= "string" or emoji == "" then return nil end
	local key = BY_EMOJI[emoji]
	if key then return ID[key] end
	-- A call site may pass "ðŸ§¬ DNA" rather than a bare glyph -- the Button and Card helpers
	-- concatenate an icon onto its text. Matching the leading glyph costs one substring compare per
	-- distinct length, and the alternative is every caller learning to split its own string.
	--
	-- Descending, so that "âš”ï¸" (two code points, 6 bytes with the variation selector) is tried
	-- before "âš”" (3 bytes) -- otherwise the shorter prefix always wins and the selector is left
	-- dangling on the front of the remaining text.
	for _, n in ipairs({ 8, 7, 6, 4, 3 }) do
		local head = emoji:sub(1, n)
		local hit = BY_EMOJI[head]
		if hit then return ID[hit] end
	end
	return nil
end

function IconLibrary.Has(emoji)
	return IconLibrary.Resolve(emoji) ~= nil
end

-- Strips a leading mapped emoji (and the space after it) off a label, so a caption that reads
-- "ðŸ§¬ DNA" becomes "DNA" once the glyph has been replaced by a drawn icon beside it. Returns the
-- string untouched when nothing was stripped, so it is safe to call on anything.
function IconLibrary.StripLeading(text)
	if type(text) ~= "string" then return text end
	for _, n in ipairs({ 8, 7, 6, 4, 3 }) do
		if BY_EMOJI[text:sub(1, n)] then
			-- one optional space, not `%s*`: a caption is allowed to start with an indent and eating
			-- it would silently reflow the label
			local rest = text:sub(n + 1)
			return (rest:sub(1, 1) == " ") and rest:sub(2) or rest
		end
	end
	return text
end

return IconLibrary

