--[[
	IconLibrary -- the asset layer the HUD never had (ROADMAP 9.9).

	Before this, every icon in the game was an EMOJI IN A TEXTLABEL. A tree scan found zero
	ImageLabels and zero rbxassetid strings in the whole interface. That is not a style choice, it
	is a different picture on every platform: Windows, Android, iOS and console each ship their own
	emoji font, so the same tile renders four ways and not one of them shares the thick dark
	outline and flat pastel fill that every other surface in this game is built from.

	The art is generated by `tools/make_icons.py` and uploaded once; `assets/icons/uploaded.json`
	is the record of that upload and this table is what the game reads. Regenerating a PNG does not
	change its asset id -- if the art moves, it has to be uploaded again and the id replaced here.

	===== THE ONE RULE THAT MATTERS: LOOKUP IS BY EMOJI =====

	`BY_EMOJI` maps the emoji a call site ALREADY passes to an icon. Nothing else was possible at a
	sane cost: emojis are written in `GameConfig` rows (twenty stages, a hundred pet species, nine
	passes, seventeen products, thirty season rewards), in `MainUI`, and in payloads the server
	sends the client. Threading an `iconKey` field through all of those would be a hundred edits
	and every one of them a chance to miss a row.

	So a call site keeps saying "\u{1F9EC}" and gets a drawn double helix. The emoji stays in the
	source as what it always was -- a legible name for the thing -- and becomes the KEY as well.

	===== AND WHY AN UNMAPPED EMOJI IS NOT A BUG =====

	`Resolve` returns nil for anything it does not know, and every call site draws the emoji when it
	does. That is the whole fallback, and it is what makes this safe to ship half-finished:

	  * 128 distinct emojis exist across the client and GameConfig, and ~90 of them are SPECIES
	    IDENTITY -- a Swarmer is a bug, a pet is a fox. Those are not interface chrome and they are
	    not worth 90 more uploads; they are also the ones where the platform emoji is genuinely
	    good, because it is a picture of an animal drawn by a type foundry.
	  * A new emoji added to GameConfig next year renders exactly as it does today until somebody
	    adds a row here. It can never render as nothing, which is the failure mode an asset layer
	    normally introduces (see the SoundLibrary header: a moderated asset is not an error, it is
	    silence -- and here it would be an empty square).

	Same reason `Has` exists rather than call sites comparing against nil themselves.
]]

local IconLibrary = {}

-- ===== THE ASSETS =====
-- Names match `tools/make_icons.py` and `assets/icons/uploaded.json` exactly. Do not rename one
-- without the other two.
--
-- STORE ASSETS ARE MARKED `-- store`, and they are NOT uploads of our own art. They have NO
-- `assets/icons/*.png` behind them at all -- several (`book`, `zone`, `dna`, `gift`, `paw`, `plus`,
-- `potion`, `shop`, `upgrade`, `wheel`, `bolt`, `backpack`) STILL have a house PNG on disk showing a
-- DIFFERENT PICTURE, so redrawing one and re-uploading it silently swaps the HUD back to the house
-- look. `zone` also has the word "Teleport" baked into the artwork, which is why the Zones tile reads
-- "Teleport" above its own "Zones" caption.
--
-- Kristina inserted them as a stack of Decals (they nest, because a Decal dropped on a Decal
-- parents to it). The stack is the source of every `-- store` id below. It used to sit in
-- WORKSPACE, where a Decal with no parent Part renders nothing but the pile still counted as world
-- geometry; it now lives in `ServerStorage.SourceProps.IconDecals` with the rest of the raw art.
-- Nothing reads it at run time -- these ids are already copied into the table below, and the pile
-- is kept only so the source art can be found again.
--
-- STILL IN THAT PILE AND NOT WIRED, kept here so nothing is lost if it is ever deleted -- these are
-- ids, not endorsements. Each one needs a caller before it earns a row in `ID`; an id with no caller
-- is the exact failure `tools/apply_uploads.py` audits for:
--   invite friends 106176247553587   quest target 12600726983   news 12600693619
--   RNG dice 138904672713663         2x pass 87223429981926
--   orange DNA 91710505122330        yellow DNA 140169929215726  red DNA 135886260297010
--   purple DNA 83100327236925
--
-- The four spare DNA colours are the interesting ones: `dna` is one glyph doing four jobs (the
-- currency pill, the Auras header, the DNA potion, the Splicer) and they could be told apart.
local ID = {
	absolute     = "rbxassetid://133654512361485",
	arrow        = "rbxassetid://100683138086656",
	audio        = "rbxassetid://77987918035205",
	aura         = "rbxassetid://73493679165170",   -- store
	-- THE SEVEN AURA TIERS (18.20). One drawing per `GameConfig.Mutations` rank, and they are picked
	-- to agree with `mut.color` rather than with the rarity NAME -- Secret is near-black and Godly is
	-- near-white, so a set sorted by "how fancy" would put the two brightest images four rows apart.
	-- Reached through `IconLibrary.AuraIcon(name)`, never through `Resolve`: a mutation row carries no
	-- emoji, so there is no key for the emoji table to hold.
	aura_common    = "rbxassetid://904513526",      -- store, pale wisp
	aura_rare      = "rbxassetid://1393222319",     -- store, blue cloud
	aura_epic      = "rbxassetid://986954285",      -- store, violet flame
	aura_legendary = "rbxassetid://1216336525",     -- store, gold flare
	aura_mythic    = "rbxassetid://567502351",      -- store, red lightning
	aura_secret    = "rbxassetid://1280932391",     -- store, dark blue arc
	aura_godly     = "rbxassetid://3733610821",     -- store, white burst
	backpack     = "rbxassetid://12600727274",      -- store, and the id the Inventory tile already used
	bag          = "rbxassetid://86141762589488",
	blackhole    = "rbxassetid://86622214176705",
	bolt         = "rbxassetid://12600837039",      -- store
	book         = "rbxassetid://75827505162710",   -- store
	boom         = "rbxassetid://98622443720558",
	boss         = "rbxassetid://75913353547225",
	calendar     = "rbxassetid://114216417880572",
	cart         = "rbxassetid://120268752774798",
	check        = "rbxassetid://139079900516571",
	clock        = "rbxassetid://110502368703038",
	coin         = "rbxassetid://138155477964656",
	cross        = "rbxassetid://79209920954791",
	crown        = "rbxassetid://100737784411045",
	desert       = "rbxassetid://107579072515574",
	diamond      = "rbxassetid://94306408327096",
	-- DNA IS THE GAME'S NAME AND ITS CURRENCY, so it gets the drawn helix rather than the house glyph.
	-- Blue of the five in the pile: the base palette is dark grey + neon blue + purple, and this one
	-- glyph lands on the DNA pill, the Auras header, the DNA potion and every income toast.
	dna          = "rbxassetid://108366319686153",  -- store
	dream        = "rbxassetid://84498845488665",
	egg          = "rbxassetid://85200417748395",
	fire         = "rbxassetid://114362288516361",
	forest       = "rbxassetid://139549052766790",
	galaxy       = "rbxassetid://73608735294271",
	gear         = "rbxassetid://134940823652825",
	gift         = "rbxassetid://111576444061359",  -- store
	handshake    = "rbxassetid://105809271165337",
	heart        = "rbxassetid://103783313754607",
	home         = "rbxassetid://117910760992150",
	honey        = "rbxassetid://114133034277624",
	hourglass    = "rbxassetid://136044741795897",
	lock         = "rbxassetid://128372983391438",
	luck         = "rbxassetid://140260937065697",
	map          = "rbxassetid://106964707289711",
	mars         = "rbxassetid://76391200725920",
	medal        = "rbxassetid://79294732633106",
	medal_bronze = "rbxassetid://116258111831735",
	medal_silver = "rbxassetid://126119579368347",
	mirror       = "rbxassetid://112502828175923",
	moon         = "rbxassetid://99231498307217",
	multiverse   = "rbxassetid://86591318170427",
	nebula       = "rbxassetid://102108182273845",
	ocean        = "rbxassetid://73127498026523",
	orb          = "rbxassetid://96092681500201",
	party        = "rbxassetid://123272919810963",
	paw          = "rbxassetid://4871217186",       -- store
	pet          = "rbxassetid://75752760135035",
	plus         = "rbxassetid://75590499344429",   -- store
	potion       = "rbxassetid://75203508047474",   -- store, and the same bottle `PotionKinds.dna` uses
	quantum      = "rbxassetid://100109299598613",
	question     = "rbxassetid://84165149952604",
	rainbow      = "rbxassetid://72918578421395",
	rebirth      = "rbxassetid://137919423177940",
	robux        = "rbxassetid://79711214319288",   -- store
	shard        = "rbxassetid://93975864077659",
	shop         = "rbxassetid://12600726809",      -- store, the market stall
	singularity  = "rbxassetid://76125474367091",
	skull        = "rbxassetid://124856616676295",
	sleep        = "rbxassetid://126193952793647",
	snow         = "rbxassetid://105381723604694",
	sparkle      = "rbxassetid://79993776154604",
	speed        = "rbxassetid://83909543865551",
	sprig        = "rbxassetid://137694586619038",
	sun          = "rbxassetid://128063910082223",
	sword        = "rbxassetid://77111451475226",
	ticket       = "rbxassetid://102723710825138",
	upgrade      = "rbxassetid://94633314888299",   -- store
	void         = "rbxassetid://86778432912380",
	volcano      = "rbxassetid://116235909195170",
	warning      = "rbxassetid://98782266115018",
	wheel        = "rbxassetid://121390188581874",  -- store
	wormhole     = "rbxassetid://83004249894908",
	xp           = "rbxassetid://90055084700953",
	zone         = "rbxassetid://77905538933584",   -- store
}
IconLibrary.Id = ID

-- ===== MUTATION RANK -> AURA ICON =====
-- By NAME, not by index: `GameConfig.Mutations` is rank-ordered and a tier inserted in the middle
-- would silently shift every drawing down one row if this were positional.
local BY_MUTATION = {
	Common = "aura_common", Rare = "aura_rare", Epic = "aura_epic", Legendary = "aura_legendary",
	Mythic = "aura_mythic", Secret = "aura_secret", Godly = "aura_godly",
}

-- Returns the aura drawing for a mutation name, or nil for one this table has never heard of --
-- the same contract as `Resolve`, so a mutation added to GameConfig next year draws its colour chip
-- alone rather than an empty square.
function IconLibrary.AuraIcon(mutationName)
	local key = BY_MUTATION[mutationName]
	return key and ID[key] or nil
end

-- ===== EMOJI -> ICON =====
--
-- Several emojis deliberately share an icon. That is not laziness: ⏰ ⏳ ⌛ ⏱️ are four drawings of
-- one idea ("time"), and a set where every near-synonym gets its own subtly different clock is
-- harder to read at 40 px than one where they all get the same one. The exception is where the
-- game gives two of them DIFFERENT MEANINGS -- ⭐ is Evolution XP and 🌟 is an Evolution Shard, and
-- those two sit next to each other on the Daily panel, so they are a five-point star and a
-- four-point sparkle and must never be merged.
local BY_EMOJI = {
	-- currencies and stats
	["\u{1F9EC}"] = "dna",       -- 🧬
	["\u{1F48E}"] = "diamond",   -- 💎
	["\u{1F31F}"] = "shard",     -- 🌟  (Evolution Shard -- NOT the same as ⭐)
	["\u{2B50}"]  = "xp",        -- ⭐  (Evolution XP)
	["\u{1F340}"] = "luck",      -- 🍀
	["\u{1F4B0}"] = "coin",      -- 💰
	["\u{2694}\u{FE0F}"] = "sword",   -- ⚔️
	["\u{2694}"]  = "sword",          -- the same emoji written without its variation selector
	["\u{1F4A5}"] = "boom",      -- 💥
	["\u{2764}\u{FE0F}"] = "heart",   -- ❤️
	["\u{1F49C}"] = "heart",     -- 💜

	-- inventory and shops
	["\u{1F6D2}"] = "cart",      -- 🛒
	-- 🛍️ IS THE ROBUX SHOP, NOT A SHOPPING BAG. Every 🛍️ in the game is a Robux surface: the HUD
	-- tile, the panel title, the purchase toast, the zone shop's sign and the Shops.lua row. So it
	-- draws the Robux logo. `bag` keeps its own drawing but now has no caller -- like `map`.
	["\u{1F6CD}\u{FE0F}"] = "robux",  -- 🛍️
	["\u{1F6CD}"] = "robux",
	["\u{1FA84}"] = "aura",           -- 🪄  the Auras tile (it borrowed the DNA glyph before)
	["\u{1F3EA}"] = "shop",      -- 🏪
	["\u{1F392}"] = "backpack",  -- 🎒
	["\u{1F9EA}"] = "potion",    -- 🧪
	["\u{2697}\u{FE0F}"] = "potion",  -- ⚗️
	["\u{2697}"]  = "potion",
	["\u{1F95A}"] = "egg",       -- 🥚
	["\u{1F423}"] = "egg",       -- 🐣
	["\u{1F43E}"] = "paw",       -- 🐾

	-- navigation and screens
	["\u{1F4D2}"] = "book",      -- 📒
	["\u{1F4D6}"] = "book",      -- 📖
	["\u{1F5FA}\u{FE0F}"] = "zone",   -- 🗺️  the Zones tile and panel header (the only 🗺️ in the game)
	["\u{1F5FA}"] = "zone",
	["\u{267B}\u{FE0F}"] = "rebirth", -- ♻️
	["\u{267B}"]  = "rebirth",
	["\u{1F50A}"] = "audio",     -- 🔊
	["\u{1F3A1}"] = "wheel",     -- 🎡
	["\u{1F39F}\u{FE0F}"] = "ticket", -- 🎟️
	["\u{1F39F}"] = "ticket",
	["\u{1F381}"] = "gift",      -- 🎁
	["\u{1F4C5}"] = "calendar",  -- 📅
	["\u{1F389}"] = "party",     -- 🎉

	-- state and feedback
	["\u{1F512}"] = "lock",      -- 🔒
	["\u{2713}"]  = "check",     -- ✓
	["\u{2714}\u{FE0F}"] = "check",   -- ✔️
	["\u{274C}"]  = "cross",     -- ❌
	["\u{2753}"]  = "question",  -- ❓
	["\u{2757}"]  = "question",  -- ❗
	["\u{2B06}\u{FE0F}"] = "upgrade", -- ⬆️
	["\u{2B06}"]  = "upgrade",
	["\u{27A1}\u{FE0F}"] = "arrow",   -- ➡️
	["\u{27A1}"]  = "arrow",
	["\u{2192}"]  = "arrow",     -- →
	["\u{2795}"]  = "plus",      -- ➕
	["\u{1F525}"] = "fire",      -- 🔥
	["\u{26A1}"]  = "bolt",      -- ⚡
	["\u{2699}\u{FE0F}"] = "gear",    -- ⚙️
	["\u{2699}"]  = "gear",
	["\u{1F308}"] = "rainbow",   -- 🌈
	["\u{2600}\u{FE0F}"] = "sun",     -- ☀️
	["\u{2600}"]  = "sun",
	["\u{1F451}"] = "crown",     -- 👑
	["\u{1F3C5}"] = "medal",     -- 🏅
	["\u{1F947}"] = "medal",     -- 🥇
	["\u{1F479}"] = "boss",      -- 👹
	["\u{1F408}"] = "pet",       -- 🐈
	["\u{1F431}"] = "pet",       -- 🐱

	-- TIME. Four emojis, one idea, one drawing -- see the note above this table.
	["\u{23F0}"] = "clock",      -- ⏰
	["\u{23F3}"] = "hourglass",  -- ⏳
	["\u{231B}"] = "hourglass",  -- ⌛
	["\u{23F1}\u{FE0F}"] = "clock",   -- ⏱️
	["\u{23F1}"] = "clock",

	-- ========================================================================
	-- THE ZONES (10.20)
	-- ========================================================================
	-- Seventeen of the twenty zones had no art and fell back to a platform glyph. These are the
	-- BIGGEST icons in the game and it is easy to miss why: the same drawing is used on the zone
	-- row, on the unlock toast, on the boss bar -- and on `ZoneTransition`'s full-screen card,
	-- where it renders at 190x190. Everything else here is read at forty pixels.
	--
	-- THE BOSS ROWS ARE THE SAME EMOJI ON PURPOSE. `GameConfig.ZoneBosses` reuses each zone's glyph
	-- for that zone's boss from Volcano onward, so one drawing lights both places with no extra row
	-- here and nothing to keep in step.
	["\u{1F332}"] = "forest",      -- 🌲 Forest
	["\u{1F3DC}\u{FE0F}"] = "desert",   -- 🏜️ Desert
	["\u{1F3DC}"] = "desert",
	["\u{1F30A}"] = "ocean",       -- 🌊 Ocean (and the "Deep Currents" season)
	["\u{1F30B}"] = "volcano",     -- 🌋 Volcano (and "Ashfall")
	["\u{1F319}"] = "moon",        -- 🌙 Moon
	["\u{1F534}"] = "mars",        -- 🔴 Mars
	["\u{1F30C}"] = "galaxy",      -- 🌌 Galaxy
	["\u{26AB}"]  = "blackhole",   -- ⚫ Black Hole
	["\u{1F300}"] = "multiverse",  -- 🌀 Multiverse
	["\u{1F320}"] = "nebula",      -- 🌠 Nebula (and "Starfall")
	["\u{1F573}\u{FE0F}"] = "wormhole", -- 🕳️ Wormhole
	["\u{1F573}"] = "wormhole",
	["\u{269B}\u{FE0F}"] = "quantum",   -- ⚛️ Quantum Realm
	["\u{269B}"]  = "quantum",
	["\u{1F4AD}"] = "dream",       -- 💭 Dream Dimension
	["\u{1FA9E}"] = "mirror",      -- 🪞 Mirror Universe
	["\u{1F311}"] = "void",        -- 🌑 Void Expanse
	["\u{1F4AB}"] = "singularity", -- 💫 Singularity
	["\u{1F53A}"] = "absolute",    -- 🔺 The Absolute Plane

	-- ========================================================================
	-- CHROME THAT WAS STILL FALLING BACK TO A GLYPH (10.20)
	-- ========================================================================
	-- Found by auditing every emoji that reaches a tile, a pill or a header against this table.
	-- Several are NEAR-MISSES of rows that already existed -- a second tick glyph, a bare ✔ with no
	-- variation selector, a dagger where the rest of the game uses crossed swords -- and those cost
	-- a row each and no art at all. They are grouped with the icon they join.
	["\u{2705}"]  = "check",     -- ✅ the Claimed / Done / Premium-unlocked marks
	["\u{2714}"]  = "check",     -- ✔  bare, no variation selector: the pet Equipped tick
	["\u{2715}"]  = "cross",     -- ✕  the pet Release button
	["\u{1F5E1}\u{FE0F}"] = "sword",  -- 🗡️ the pet card's Damage stat
	["\u{1F5E1}"] = "sword",
	["\u{1F4CB}"] = "book",      -- 📋 the Season panel's Quests tab
	["\u{1F948}"] = "medal_silver",   -- 🥈 leaderboard 2nd
	["\u{1F949}"] = "medal_bronze",   -- 🥉 leaderboard 3rd
	-- ⚠ and its selector-less twin: the caution line under the pet Fuse row
	["\u{26A0}\u{FE0F}"] = "warning",
	["\u{26A0}"]  = "warning",
	["\u{1F4A4}"] = "sleep",     -- 💤 the offline-earnings card
	["\u{2620}\u{FE0F}"] = "skull",   -- ☠️ the boss-revive prompt
	["\u{2620}"]  = "skull",
	["\u{2728}"]  = "sparkle",   -- ✨ the season track's shard face, and "NEW FORM"
	["\u{1F52E}"] = "orb",       -- 🔮 the Mystery Potions shop
	["\u{1F91D}"] = "handshake", -- 🤝 "Trade complete!"
	["\u{1F3E0}"] = "home",      -- 🏠 the arena's Back portal
	["\u{2744}\u{FE0F}"] = "snow",    -- ❄️ the "Frostbloom" season
	["\u{2744}"]  = "snow",
	["\u{1F33F}"] = "sprig",     -- 🌿 the "Overgrowth" season
	["\u{1F36F}"] = "honey",     -- 🍯 the Large potion size
	-- SPEED IS ONE DRAWING FOR TWO GLYPHS, and they are the same idea told twice: 👟 is the Speed
	-- UPGRADE tile and 🏃 is the 2x Speed PASS chip. Before this, the pass chip was the one chip in
	-- a grid of nine that kept a glyph while its neighbours had art.
	["\u{1F45F}"] = "speed",     -- 👟
	["\u{1F3C3}"] = "speed",     -- 🏃

	-- `zone` IS DELIBERATELY LEFT WITH NO EMOJI, and it is the one entry in `ID` that has none.
	-- It was orphaned by accident before 10.20 -- drawn, uploaded and unreachable, which is the
	-- failure `tools/apply_uploads.py` now audits for -- and it stays unmapped on purpose now that
	-- all twenty zones have their own art: a generic green landscape would only ever be shown
	-- INSTEAD of the specific zone, which is worse than the emoji fallback. Kept rather than
	-- deleted because it costs one line and is the obvious drawing for any future "somewhere in
	-- the world" label.
}

-- Returns the asset id for an emoji, or nil when there is no icon for it -- which is a normal
-- answer, not a failure. See the header.
function IconLibrary.Resolve(emoji)
	if type(emoji) ~= "string" or emoji == "" then return nil end
	local key = BY_EMOJI[emoji]
	if key then return ID[key] end
	-- A call site may pass "🧬 DNA" rather than a bare glyph -- the Button and Card helpers
	-- concatenate an icon onto its text. Matching the leading glyph costs one substring compare per
	-- distinct length, and the alternative is every caller learning to split its own string.
	--
	-- Descending, so that "⚔️" (two code points, 6 bytes with the variation selector) is tried
	-- before "⚔" (3 bytes) -- otherwise the shorter prefix always wins and the selector is left
	-- dangling on the front of the remaining text.
	for _, n in ipairs({ 8, 7, 6, 4, 3 }) do
		local head = emoji:sub(1, n)
		local hit = BY_EMOJI[head]
		if hit then return ID[hit] end
	end
	return nil
end

function IconLibrary.Has(emoji)
	return IconLibrary.Resolve(emoji) ~= nil
end

-- Strips a leading mapped emoji (and the space after it) off a label, so a caption that reads
-- "🧬 DNA" becomes "DNA" once the glyph has been replaced by a drawn icon beside it. Returns the
-- string untouched when nothing was stripped, so it is safe to call on anything.
function IconLibrary.StripLeading(text)
	if type(text) ~= "string" then return text end
	for _, n in ipairs({ 8, 7, 6, 4, 3 }) do
		if BY_EMOJI[text:sub(1, n)] then
			-- one optional space, not `%s*`: a caption is allowed to start with an indent and eating
			-- it would silently reflow the label
			local rest = text:sub(n + 1)
			return (rest:sub(1, 1) == " ") and rest:sub(2) or rest
		end
	end
	return text
end

return IconLibrary
