--[[
	FirstJoin -- the first two minutes of the game, guided (Phase 6.3, restyled 18.22 and 18.23).

	Zones 1 and 2 were designed as a tutorial stretch and then nothing ever told the player that.
	A new arrival landed in Forest with twenty-odd buttons, no idea that DNA comes from hitting the
	creatures walking past, and an EVOLVE button that says "not enough DNA" until they work out why.

	Three beats, and they are the roadmap's own: a camera pan that shows the street, an arrow that
	names the next thing to do, and the first evolve -- which `EvolveReveal` already celebrates, so
	this file gets out of the way rather than adding a second card on top of it. 18.23 added a
	fourth: the climb, which is the one thing in this world nobody finds on their own.

	What is on screen, end to end: a smooth camera pan over the starting Forest; a marching neon
	chevron trail on the ground running to the nearest live creature; a floating beacon and a
	Highlight on that creature; a pulsing halo and a bouncing arrow on the EVOLVE button when it is
	finally pressable; and one banner card carrying the step, its reason, and three progress pips.

	=========================================================================================
	WHAT DECIDES WHETHER THIS RUNS
	=========================================================================================
	`data.TutorialDone`, a real field in the save, flipped by the SERVER on the first evolve. Not
	"is this player at stage 1": a rebirth resets StageIndex to 1, so that test would replay the
	whole sequence for a veteran every time they reset. And not a client-side "I have finished"
	report, because a client that can say that can say it having never played.

	=========================================================================================
	THE THREE THINGS THAT WOULD LEAVE A PLAYER STUCK
	=========================================================================================
	1. A SCRIPTABLE CAMERA THAT IS NEVER GIVEN BACK. Everything the pan touches is restored in one
	   block that runs whether the pan finished, errored, or was skipped -- and the restore is the
	   `Custom` camera type plus the humanoid as subject, i.e. the state the engine sets up itself,
	   not a CFrame this file guessed. A failure halfway through otherwise leaves that player
	   looking at scenery with no way out but a rejoin.
	2. A GUIDE THAT WILL NOT LET GO. Any input at all skips the pan. Nobody who already knows this
	   game should have to watch three seconds of it, and a player who is pressing keys is telling
	   you exactly that.
	3. HEARTBEAT, NEVER RENDERSTEPPED. `RenderStepped:Wait()` never returns on a client that is not
	   rendering, and the whole sequence would hang inside its own pcall with no error anywhere --
	   see HatchReveal's header, which is where that cost an hour.

	=========================================================================================
	18.22 -- THE RESTYLE, AND WHAT THE "TUTORIAL BUILDER" PLUGIN ACTUALLY CONTRIBUTED
	=========================================================================================
	Asked for as *"dodala sam ti i tutorial builder u pluginovima, probaj to iskoristiti za tutorial
	da izgleda bolje, strelice i text i sve"*. The plugin (Tutorial Builder, @Jobble Games) was read
	rather than guessed at: its installed `Plugin.rbxm` was decompressed off disk and its single
	`TutorialMaker` script read end to end. Three things came out of that, and they decided the shape
	of this file.

	  1. IT HAD WRITTEN NOTHING. The plugin persists its step list to `ServerStorage.InGameTutorialData`
	     and exports a `StarterPlayerScripts.AutoGeneratedTutorialScript`. Neither instance exists in
	     this place -- the plugin is installed and has never been given a step. So there was no
	     authored content to import; there was only a FORMAT.
	  2. ITS OUTPUT COULD NOT BE USED AS-IS, and not merely on taste. The generated script is a
	     `Color3.fromRGB(20,20,20)` rectangle with no corner radius, no stroke and no gradient, set in
	     **Gotham** -- beside this game's FredokaOne-on-ink-outline surfaces it reads as a different
	     game's debug overlay. It is also ungated: it calls `showStep(1)` unconditionally on every
	     join for every player, with no equivalent of `TutorialDone`, so a veteran would be handed the
	     new-player wizard every single time they logged in. And its world arrow is a `Beam` textured
	     with `rbxassetid://15174447092`, which was probed live in this place and came back
	     **`IsLoaded = false`**, with `InsertService:LoadAsset` refusing it outright ("Asset is not
	     trusted for this place"). The plugin's arrows would have drawn nothing at all here.
	  3. ITS ONE GOOD IDEA WAS THE WORLD-SPACE TRAIL. A line of arrowheads marching from the player
	     toward the thing they are being told to go and hit is a genuinely better answer than a single
	     marker hanging over the target, because it is readable from behind, from the side, and while
	     you are running. That idea is taken. The Beam-plus-toolbox-texture MECHANISM is not, for the
	     measured reason above.

	So: the plugin's step SCHEMA (an ordered list of steps, each with text, an optional icon, and an
	optional named arrow target) is what `STEPS` below is shaped like, and every pixel of it is drawn
	with this game's own `CardKit` and `UITheme` instead of with the plugin's generator. The
	interaction model stays this file's rather than the plugin's: no "Next" button, because the step
	is DERIVED from the save every tick (see `stepFor`) and a player who evolves has already moved on
	without needing to dismiss anything.

	===== AND WHY THE CHEVRONS ARE GEOMETRY RATHER THAN A PICTURE =====

	Same argument the on-screen arrow below has always carried: an asset id is one more thing that can
	be moderated away or simply refused by the place, which is exactly what happened to the plugin's.
	`Enum.MeshType.Pyramid` is engine geometry -- it cannot fail to load, it needs no upload, and it
	orients along a CFrame, which a camera-facing glyph cannot do. Probed on this build before it was
	used.

	=========================================================================================
	A NOTE ON THIS FILE'S OWN HISTORY, BECAUSE IT IS THE POINT OF THE COMMENTS (19.6)
	=========================================================================================
	The 18.23 pass compacted this file from 915 lines to 674 and took 201 comment lines with it,
	leaving the header above as a five-line feature list. 19.0 established that the compacted copy
	was the DESCENDANT -- it holds real work (the sound cues, the halo, the vertical pips) -- so the
	restoration is a merge onto it rather than a revert, and every number quoted below was re-read
	off the code beside it rather than copied back from the old file.

	It was filed as documentation debt. It was not only that: the compaction also dropped two guards
	from `runClimbBeat`, and one of them is a live defect. See the block over that function.
--]]

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local RS = game:GetService("ReplicatedStorage")

local GameConfig = require(RS:WaitForChild("Modules"):WaitForChild("GameConfig"))
local UITheme = require(RS.Modules:WaitForChild("UITheme"))
local CardKit = require(RS.Modules:WaitForChild("HUD"):WaitForChild("CardKit"))
local IconLibrary = require(RS.Modules:WaitForChild("IconLibrary"))
local SoundLibrary = require(RS.Modules:WaitForChild("SoundLibrary"))

local player = Players.LocalPlayer
local Remotes = RS:WaitForChild("Remotes")

local STEP = RunService.Heartbeat

local PAN_TIME = 3.4
local ARROW_BOB = 12          -- pixels the arrow travels up and down
local DONE_BANNER_TIME = 4.2
local CLIMB_BEAT_TIME = 7.0

local state = {
	data = nil,
	panned = false,           -- once per session, not once per payload
	climbShown = false,       -- the fourth beat is a one-shot; see runClimbBeat
	running = false,
}

-- ============================================================================
-- THE STEP TABLE -- THE PLUGIN'S SCHEMA, THIS GAME'S CONTENT (18.22)
-- ============================================================================
-- One row per beat, in the order they happen. This is deliberately the same shape the Tutorial
-- Builder plugin persists (`{ text = ..., image = ..., arrowTargetName = ... }`) so that if the
-- owner ever does author steps in its dock widget, importing them is a field rename and not a
-- rewrite -- but every row here is drawn by `paint` below, in FredokaOne on a studded ink-outlined
-- card, rather than by the plugin's Gotham generator.
--
-- `icon` is an EMOJI rather than an asset id, and it is resolved through `IconLibrary.Resolve` at
-- draw time. That call returns nil for anything it has no drawing for, and the contract every call
-- site in this codebase honours is "draw the emoji when it does" -- so a beat whose icon has not been
-- illustrated yet still shows something rather than an empty square.
--
-- `tone` is a palette PAIR, not a single colour: every surface in this game is a two-stop gradient
-- and a flat fill is the one thing that reads as "somebody skipped the theme".
local STEPS = {
	fight = {
		key = "fight",
		icon = "\u{2694}\u{FE0F}",                      -- crossed swords
		headline = "Attack a creature",
		subline = "Click one to fight it and earn XP",
		tone = { UITheme.Color.Lavender, UITheme.Color.Purple },
	},
	evolve = {
		key = "evolve",
		icon = "\u{2B50}",                              -- star
		headline = "You are ready to EVOLVE!",
		subline = "Press the shiny EVOLVE button",
		tone = { UITheme.Color.Sunny, UITheme.Color.Orange },
	},
	done = {
		key = "done",
		icon = "\u{1F389}",                             -- party popper
		headline = "Evolved!",
		subline = "Keep fighting -- new zones open as you grow",
		tone = { UITheme.Color.Mint, UITheme.Color.Green },
	},
	climb = {
		key = "climb",
		icon = "\u{26F0}\u{FE0F}",                      -- mountain
		headline = "Climb to the next terrace",
		subline = "Tougher creatures, higher XP drops",
		tone = { UITheme.Color.Aqua, UITheme.Color.Blue },
	},
}

-- The three dots on the card are the three beats a NEW player walks through, in order. `done` is not
-- one of them: it is the confirmation that beat 2 landed, not a fourth thing to do.
local DOT_ORDER = { "fight", "evolve", "climb" }

-- ============================================================================
-- THE CAMERA PAN
-- ============================================================================
local function panCamera()
	local character = player.Character or player.CharacterAdded:Wait()
	local root = character:WaitForChild("HumanoidRootPart", 10)
	local humanoid = character:FindFirstChildOfClass("Humanoid")
	local cam = workspace.CurrentCamera
	if not root or not cam then return end

	local skipped = false
	local conn = UserInputService.InputBegan:Connect(function()
		skipped = true
	end)

	-- Framed off the CHARACTER's own facing rather than off world axes: the spawn faces down the
	-- Forest street, and a pan written against +Z would be looking at a wall the day that changes.
	local here = root.Position
	local facing = root.CFrame.LookVector
	local startAt = here + Vector3.new(0, 62, 0) - facing * 78
	local endAt = here + Vector3.new(0, 7, 0) - facing * 18

	local ok, err = pcall(function()
		cam.CameraType = Enum.CameraType.Scriptable
		local t0 = os.clock()
		while os.clock() - t0 < PAN_TIME and not skipped do
			local a = (os.clock() - t0) / PAN_TIME
			-- eased in and out, so it settles into the over-the-shoulder shot instead of stopping
			local eased = a < 0.5 and 2 * a * a or 1 - (-2 * a + 2) ^ 2 / 2
			local at = startAt:Lerp(endAt, eased)
			-- looks at the player the whole way down, which is what makes it read as an introduction
			-- to a character rather than a flyover of some trees
			local targetPos = (player.Character and player.Character:FindFirstChild("HumanoidRootPart") or root).Position + Vector3.new(0, 2, 0)
			cam.CFrame = CFrame.lookAt(at, targetPos)
			STEP:Wait()
		end
	end)

	conn:Disconnect()

	-- THE RESTORE, on every path. Custom + the humanoid is the state the engine builds for itself;
	-- handing back a CFrame this file invented would leave the camera subtly wrong forever.
	cam.CameraType = Enum.CameraType.Custom
	if humanoid then
		cam.CameraSubject = humanoid
	end
	if not ok then
		warn("[FirstJoin] camera pan failed: " .. tostring(err))
	end
end

-- ============================================================================
-- THE GUIDE GUI
-- ============================================================================
-- Its own ScreenGui: MainUI is at Luau's 200-register ceiling (see its header) and none of this is
-- HUD state. `ResetOnSpawn = false` because dying during the tutorial is the most likely moment of
-- all to still need it.
local gui = Instance.new("ScreenGui")
gui.Name = "FirstJoinGuide"
gui.ResetOnSpawn = false
gui.DisplayOrder = 110        -- over the HUD, under the zone-transition wipe (500)
gui.Parent = player:WaitForChild("PlayerGui")

-- ============================================================================
-- ...AND IT GETS OUT OF THE WAY OF A PANEL (15.20)
-- ============================================================================
-- `DisplayOrder` beats `ZIndex` ACROSS ScreenGuis, and it does so absolutely: this gui is at 110
-- and `EvolutionLabUI` never sets one at all, so it is at 0. No ZIndex a panel can choose will ever
-- put it over this banner. Photographed on both clients of the two-client run: "⚔️ Click a creature
-- to attack it" sat across the trade window covering BOTH offer column headers, and across the
-- trade picker's header.
--
-- Lowering `DisplayOrder` is the wrong fix -- the 110 is deliberate, because the arrow points at
-- the EVOLVE button and the banner has to clear the HUD it is talking about. What is actually true
-- is that a panel is a MODAL surface: while one is open the guide is both wrong and in the way.
--
-- So the whole gui is disabled rather than each piece hidden. One watcher, and none of the
-- visibility logic below it has to learn about panels -- including the two one-shot timed banners
-- (`TutorialDone` and the climb beat), which set `Visible` once and would otherwise each need
-- their own guard.
--
-- 18.22: THE WORLD TRAIL IS SWITCHED OFF BY THE SAME WATCHER, and it has to be explicitly, because
-- it is the one part of this guide that is NOT a child of `gui`. Chevrons are Parts in `workspace`
-- (a ScreenGui cannot hold geometry), so `gui.Enabled = false` does not reach them -- without the
-- second line here a player who opened the shop mid-tutorial would get a modal panel with a row of
-- arrows still marching across the world behind it.
local trailSuspended = false
task.spawn(function()
	local mainGui = player.PlayerGui:WaitForChild("EvolutionLabUI", 30)
	if not mainGui then return end
	while true do
		local panelOpen = false
		-- direct children only: `registerPanel` stamps `HudPanel` on the panel itself, and every
		-- one of them is parented straight to the ScreenGui
		for _, child in ipairs(mainGui:GetChildren()) do
			if child:GetAttribute("HudPanel") and child.Visible then
				panelOpen = true
				break
			end
		end
		gui.Enabled = not panelOpen
		trailSuspended = panelOpen
		task.wait(0.15)
	end
end)

-- ============================================================================
-- THE FLOATING BANNER CARD (18.22)
-- ============================================================================
-- What was here before was a `Frame` painted flat `UITheme.Color.Purple` with a 16 px corner and a
-- 4 px stroke, holding one `TextScaled` line. It was the only surface in the game built that way:
-- every panel, tile and row the player sees is an ink-outlined, stud-textured, two-stop gradient
-- card, and the one thing that greets a brand new player was the one thing that did not look like
-- the game. That is the whole complaint behind *"da izgleda bolje"*.
--
-- Drawn through `CardKit` rather than by hand, for the reason CardKit's own header gives: it is the
-- panel language extracted so other surfaces can speak it, and a card drawn half through `CardKit`
-- and half through `UIKit.styleCard` inherits two different stacking schemes. One card, one kit.
--
-- The layout is a THREE-COLUMN row rather than a centred line, and that is what buys the second line
-- of text. A single `TextScaled` string had to say the verb and the reason in one breath ("⚔️ Click a
-- creature to attack it") and scaled itself down to fit; splitting it into a headline at a fixed
-- 24 px and a subline at 17 px means the instruction is read first and the explanation second, at
-- sizes that do not move when the sentence changes length.
local banner = Instance.new("Frame")
banner.Name = "Banner"
banner.AnchorPoint = Vector2.new(0.5, 0)
banner.Position = UDim2.new(0.5, 0, 0, 128)
banner.Size = UDim2.new(0, 560, 0, 104)
banner.BackgroundTransparency = 1
banner.Visible = false
banner.ZIndex = 2
banner.Parent = gui

local card, setCardTone = CardKit.Card(banner, {
	name = "Card",
	size = UDim2.new(1, 0, 1, 0),
	colors = STEPS.fight.tone,
	radius = 22,
	studTile = 26,
	studTransparency = 0.86,
	zIndex = 2,
})

-- The card is a raised object over a busy world, so it casts. `UITheme.DropShadow` is the same
-- nine-slice sprite every HUD tile uses -- reached through the theme rather than reimplemented here,
-- because the kit's header is explicit that a second copy of the shadow numbers is how "half the HUD
-- looks different" reports start. In a `pcall` because a missing shadow is a cosmetic loss and this
-- is the first thing a new player sees: it must not be what stops the guide building.
pcall(UITheme.DropShadow, card, UDim.new(0, 22))

-- ===== THE ICON CHIP =====
-- A round plate under the glyph rather than the glyph alone. A bare emoji on a gradient has no edge
-- to sit against and reads as part of the sentence beside it -- the same argument `CardKit.Pill`
-- makes about a quantity, one shape smaller.
local iconChip = Instance.new("Frame")
iconChip.Name = "IconChip"
iconChip.AnchorPoint = Vector2.new(0, 0.5)
iconChip.Position = UDim2.new(0, 14, 0.5, 0)
iconChip.Size = UDim2.new(0, 72, 0, 72)
iconChip.BackgroundColor3 = CardKit.WHITE
iconChip.BackgroundTransparency = 0.80
iconChip.BorderSizePixel = 0
iconChip.ZIndex = 4
iconChip.Parent = card
CardKit.Corner(iconChip, 999)
CardKit.Stroke(iconChip, CardKit.INK, 3)

-- BOTH DRAWINGS ARE BUILT, AND EXACTLY ONE IS EVER VISIBLE. `IconLibrary.Resolve` answers nil for an
-- emoji it has no art for, and that is a normal answer rather than a failure (see its header) -- so
-- the label is the fallback and the ImageLabel is the upgrade. Building both once and toggling
-- `Visible` is what keeps `paint` free of instance creation: it runs on a step change, and a painter
-- that makes instances leaks one per repaint.
local iconImage = Instance.new("ImageLabel")
iconImage.Name = "IconImage"
iconImage.AnchorPoint = Vector2.new(0.5, 0.5)
iconImage.Position = UDim2.new(0.5, 0, 0.5, 0)
iconImage.Size = UDim2.new(0, 48, 0, 48)
iconImage.BackgroundTransparency = 1
iconImage.ScaleType = Enum.ScaleType.Fit
iconImage.Visible = false
iconImage.ZIndex = 5
iconImage.Parent = iconChip

local iconGlyph = Instance.new("TextLabel")
iconGlyph.Name = "IconGlyph"
iconGlyph.AnchorPoint = Vector2.new(0.5, 0.5)
iconGlyph.Position = UDim2.new(0.5, 0, 0.5, 0)
iconGlyph.Size = UDim2.new(0, 48, 0, 48)
iconGlyph.BackgroundTransparency = 1
iconGlyph.Font = UITheme.Font.Display
iconGlyph.TextScaled = true
iconGlyph.Text = ""
iconGlyph.TextColor3 = CardKit.WHITE
iconGlyph.ZIndex = 5
iconGlyph.Parent = iconChip
CardKit.Stroke(iconGlyph, CardKit.INK, 3)

local headline = CardKit.Text(card, {
	name = "Headline",
	text = STEPS.fight.headline,
	size = UDim2.new(1, -170, 0, 36),
	position = UDim2.new(0, 96, 0, 16),
	textSize = 24,
	xAlign = "Left",
	zIndex = 4,
	strokeThickness = 3,
})

local subline = CardKit.Text(card, {
	name = "Subline",
	text = STEPS.fight.subline,
	size = UDim2.new(1, -170, 0, 26),
	position = UDim2.new(0, 96, 0, 54),
	textSize = 17,
	color = UITheme.Color.Cream,
	xAlign = "Left",
	zIndex = 4,
	strokeThickness = 2,
})

-- ===== THE STEP PIPS =====
-- Three of them, down the right-hand edge. This is the one thing the plugin's linear wizard did that
-- this guide genuinely lacked: a sense of HOW MUCH IS LEFT. The old banner could tell a player what
-- to do next and never that there were only three of these -- so a new arrival had no way to know
-- whether they were being walked through a two-minute intro or a twenty-minute one.
--
-- Filled/hollow rather than a "1 / 3" caption: at this size a number is a word to read, and a column
-- of pips is a thing you take in without reading. Each is stroked in ink like every other surface
-- here so it reads as part of the card rather than as three loose circles on it.
--
-- STACKED VERTICALLY (18.23), and the reason is the card's own arithmetic rather than taste. The
-- headline and subline are both sized `(1, -170)`, i.e. they give up 170 px to the icon chip on the
-- left and this strip on the right; a horizontal row of three 14 px pips plus its padding needs
-- ~68 px of that, and a vertical column needs 20. The 48 px it gives back is what lets the two lines
-- of text run to a sensible length before `CardKit.Text` starts shrinking them.
local dotStrip = Instance.new("Frame")
dotStrip.Name = "Dots"
dotStrip.AnchorPoint = Vector2.new(1, 0.5)
dotStrip.Position = UDim2.new(1, -18, 0.5, 0)
dotStrip.Size = UDim2.new(0, 20, 0, 60)
dotStrip.BackgroundTransparency = 1
dotStrip.ZIndex = 4
dotStrip.Parent = card

local dotLayout = Instance.new("UIListLayout")
dotLayout.FillDirection = Enum.FillDirection.Vertical
dotLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
dotLayout.VerticalAlignment = Enum.VerticalAlignment.Center
dotLayout.Padding = UDim.new(0, 6)
dotLayout.Parent = dotStrip

local dots = {}
for i = 1, #DOT_ORDER do
	local dot = Instance.new("Frame")
	dot.Name = "Dot" .. i
	dot.Size = UDim2.new(0, 12, 0, 12)
	dot.BackgroundColor3 = CardKit.WHITE
	dot.BackgroundTransparency = 0.5
	dot.BorderSizePixel = 0
	dot.ZIndex = 5
	dot.Parent = dotStrip
	CardKit.Corner(dot, 999)
	CardKit.Stroke(dot, CardKit.INK, 2)
	dots[i] = dot
end

-- Repaints the whole card for a step key. Cheap enough to call every tick, but only actually called
-- when the key CHANGES (see `paintIfChanged`) -- a gradient rewritten 60 times a second is 60 times
-- the garbage for an identical picture.
local function paint(key)
	local def = STEPS[key] or STEPS.fight
	setCardTone(def.tone)
	headline.Text = def.headline
	subline.Text = def.subline

	local asset = IconLibrary.Resolve(def.icon)
	if asset then
		iconImage.Image = asset
		iconImage.Visible = true
		iconGlyph.Visible = false
	else
		iconGlyph.Text = def.icon or ""
		iconGlyph.Visible = true
		iconImage.Visible = false
	end

	-- A pip is FILLED once its beat has been reached, so the column fills top to bottom as the player
	-- moves. `done` is not in `DOT_ORDER` and deliberately lights all three: it is the moment beat two
	-- completes, and a column that emptied itself on the celebration would read as progress lost.
	--
	-- 18.23: the CURRENT beat also takes `Color.Sunny` while the ones behind it stay white. Three
	-- filled pips say how far along you are; the amber one says which of them is being asked of you
	-- right now, which is the question the card's own text is answering.
	local reached = 0
	if key == "done" then
		reached = #DOT_ORDER
	else
		for i, name in ipairs(DOT_ORDER) do
			if name == key then
				reached = i
				break
			end
		end
	end
	for i, d in ipairs(dots) do
		d.BackgroundTransparency = (i <= reached) and 0 or 0.6
		d.BackgroundColor3 = (i == reached) and UITheme.Color.Sunny or CardKit.WHITE
	end
end

local paintedKey = nil
local function paintIfChanged(key)
	if key == paintedKey then return end
	paintedKey = key
	paint(key)
	-- 18.23: a cue on the two beats that are ACHIEVEMENTS, and on neither of the two that are
	-- instructions. "fight" and "climb" are things the player is being told to go and do, and a
	-- sound on an instruction is a nag; "evolve" (you have earned it) and "done" (you did it) are
	-- the two moments worth marking. Routed through SoundLibrary rather than a local Sound so it
	-- obeys the player's own audio settings -- see the Audio panel.
	if key == "evolve" or key == "done" then
		SoundLibrary.PlayLocal("levelUp", { volume = 0.45 })
	end
end

-- ============================================================================
-- THE ON-SCREEN ARROW AND THE EVOLVE HALO
-- ============================================================================
-- The arrow is a label, not an image: an asset id is one more thing that can be moderated away, and
-- a glyph cannot fail to load. (18.22 confirmed that argument the expensive way -- the Tutorial
-- Builder plugin's own arrow texture came back `IsLoaded = false` in this place.) It is pinned to
-- the EVOLVE button's live AbsolutePosition rather than to a coordinate, so the responsive pass can
-- move that button without stranding it.
--
-- BESIDE THE BUTTON, NOT ABOVE IT, and the capture is what settled that. Above is the obvious place
-- and it is occupied: the evolve frame stacks a stage label, then the DNA/XP progress bar, then the
-- button, so a 76 px arrow hanging over the button covers the bar -- it hid the very "120 / 120 XP"
-- that explains why the player is being told to press. To the left there is nothing between the
-- evolve frame and the left-hand tile column, so the arrow points across empty screen.
local arrow = Instance.new("TextLabel")
arrow.Name = "Arrow"
arrow.AnchorPoint = Vector2.new(1, 0.5)
arrow.Size = UDim2.new(0, 76, 0, 76)
arrow.BackgroundTransparency = 1
arrow.Font = UITheme.Font.Display
arrow.TextScaled = true
arrow.Text = "\u{27A1}\u{FE0F}"
arrow.TextColor3 = UITheme.Color.White
arrow.TextStrokeColor3 = CardKit.INK
arrow.TextStrokeTransparency = 0
arrow.Visible = false
arrow.ZIndex = 4
arrow.Parent = gui
-- The same ink outline every other glyph in this game carries. `TextStrokeTransparency` alone is a
-- 1px halo; the UIStroke is the 4px one that makes it read as the same drawing as the card.
CardKit.Stroke(arrow, CardKit.INK, 4)

-- 18.23: A RING AROUND THE BUTTON ITSELF, and it is a different job from the arrow's. The arrow says
-- WHERE to look, from across the screen; the halo says THIS IS THE THING, once the eye has arrived.
-- A frame with nothing but a UIStroke, so it is a ring and not a wash over the button's own face --
-- filling it would fight the gradient underneath and make the one button the player must press
-- harder to read, not easier. Sized 4 px outside the button on every edge in the loop below.
local buttonHalo = Instance.new("Frame")
buttonHalo.Name = "ButtonHalo"
buttonHalo.BackgroundTransparency = 1
buttonHalo.BorderSizePixel = 0
buttonHalo.Visible = false
buttonHalo.ZIndex = 3
buttonHalo.Parent = gui

local haloStroke = Instance.new("UIStroke")
haloStroke.Thickness = 4.5
haloStroke.Color = UITheme.Color.Sunny
haloStroke.Transparency = 0.2
haloStroke.Parent = buttonHalo
CardKit.Corner(buttonHalo, 14)

-- IgnoreGuiInset IS DELIBERATELY LEFT FALSE, and it is the one line here that was measured wrong
-- first. The reasoning that fails: "MainUI ignores the inset, so match it." Matching makes the two
-- render alike but breaks the arithmetic, because the two quantities this file mixes do NOT share an
-- origin -- `AbsolutePosition` is reported below the topbar, while a Position OFFSET inside an
-- inset-ignoring ScreenGui is measured from the very top of the screen. Copying `true` put the arrow
-- exactly one inset (58 px, measured) above the button, which looks like a layout bug and is really a
-- unit mismatch. Left false, the offset and the AbsolutePosition it is computed from share an origin
-- and the arrow lands where the arithmetic says. The halo above is positioned the same way and
-- inherits the same requirement.
gui.IgnoreGuiInset = false

-- THE CALLER IS A HEARTBEAT, AND THE EXPENSIVE CASE IS THE ONE THAT FINDS NOTHING. Measured on
-- the live HUD at 12,317 descendants: a recursive `FindFirstChild` that HITS costs 0.0004 ms,
-- because it stops the moment it matches -- but one that MISSES walks the entire tree and costs
-- **0.1645 ms per frame, 9.9 ms every second at 60 fps**. And a miss is not the rare case: it is
-- what happens for as long as the HUD is still building, which on a first join is exactly when
-- this runs, on exactly the phone a brand-new player is holding.
--
-- So both answers are cached. A hit is held until the button is destroyed or reparented, so a HUD
-- rebuild is still picked up rather than leaving the arrow on a dead instance; a miss is held for
-- RETRY_EVERY, which turns 60 full-tree walks a second into four.
local evolveButton = nil
local nextLookup = 0
local RETRY_EVERY = 0.25
local function findEvolveButton()
	if evolveButton and evolveButton.Parent then return evolveButton end
	local now = os.clock()
	if now < nextLookup then return nil end
	nextLookup = now + RETRY_EVERY
	local host = player.PlayerGui:FindFirstChild("EvolutionLabUI")
	evolveButton = host and host:FindFirstChild("EvolveButton", true) or nil
	return evolveButton
end

-- ============================================================================
-- POINTING AT SOMETHING IN THE WORLD (9.10)
-- ============================================================================
-- The banner could always say "click a creature"; it could never say WHICH. On a street with
-- fourteen of them walking past, an instruction with no target is still a wall of text -- the row's
-- own complaint. So the guide gets one marker it can hang over any object, and one Highlight to
-- pick that object out of the crowd.
--
-- ONE OF EACH, RE-ADORNED, never one per target. Roblox draws about 31 Highlights at once and
-- CreatureService already rents fourteen of them to the creatures nearest the player (see its
-- outline pool); a guide that created its own per candidate would quietly push that budget over and
-- take outlines off the creatures it is pointing at.
--
-- The marker is a BillboardGui rather than a beam or a part: it is always the right way up, it
-- cannot be walked behind, and it needs no per-frame CFrame maths on the client.
local marker = Instance.new("BillboardGui")
marker.Name = "GuideMarker"
marker.Size = UDim2.new(0, 100, 0, 100)
marker.AlwaysOnTop = true
marker.LightInfluence = 0
marker.Enabled = false
marker.Parent = gui

local markerLabel = Instance.new("TextLabel")
markerLabel.Size = UDim2.new(1, 0, 1, 0)
markerLabel.BackgroundTransparency = 1
markerLabel.Font = UITheme.Font.Display
markerLabel.TextScaled = true
markerLabel.Text = "\u{2B07}\u{FE0F}"
markerLabel.TextColor3 = UITheme.Color.White
markerLabel.TextStrokeColor3 = CardKit.INK
markerLabel.TextStrokeTransparency = 0
markerLabel.Parent = marker
CardKit.Stroke(markerLabel, CardKit.INK, 4)

local pointHL = Instance.new("Highlight")
pointHL.Name = "GuideHighlight"
pointHL.FillTransparency = 0.70
pointHL.FillColor = UITheme.Color.Sunny
pointHL.OutlineColor = UITheme.Color.White
pointHL.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
pointHL.Enabled = false
pointHL.Parent = gui

-- ============================================================================
-- THE CHEVRON TRAIL -- THE PLUGIN'S ONE GOOD IDEA, REBUILT (18.22)
-- ============================================================================
-- A line of arrowheads leaving the player's feet and running to whatever they are being told to go
-- and do. This is what the owner meant by *"strelice"*, and it is the half of the instruction the
-- old guide could not give: a marker floating over a creature tells you where it is only once you
-- have already found it, while a trail tells you which way to TURN.
--
-- WHY IT IS NOT THE PLUGIN'S BEAM. Tutorial Builder draws this with ten `Beam` objects textured
-- `rbxassetid://15174447092`. Probed in this place before anything was written: `IsLoaded = false`,
-- and `InsertService:LoadAsset` refuses it with "Asset is not trusted for this place". Ten
-- untextured beams is ten invisible ribbons -- the plugin's arrows would simply not have appeared.
-- `Enum.MeshType.Pyramid` is engine geometry: nothing to load, nothing to moderate, and it takes a
-- CFrame, so a chevron can actually POINT rather than being a camera-facing sprite that cannot.
--
-- EVERY PART IS LOCAL, ANCHORED AND UNTOUCHABLE, on exactly the terms `RarityBeam` sets out: with
-- `CanQuery` and `CanTouch` off, a chevron can never become the answer to a combat raycast, block a
-- player, or swallow a ProximityPrompt. They live in a client-made folder and replicate nowhere.
--
-- POOLED, NEVER CREATED PER FRAME. Eight parts are made once and moved; a trail that built and
-- destroyed its geometry on a Heartbeat would churn eight instances a frame for a picture that
-- barely changes.
local CHEVRON_COUNT = 8
local CHEVRON_GAP = 7          -- studs between arrowheads along the path
local CHEVRON_START = 9        -- how far in front of the player the first one sits
local CHEVRON_ARRIVED = 14     -- inside this range the trail switches off -- you have arrived
local CHEVRON_SPEED = 9        -- studs/sec the pattern scrolls toward the target

local trailFolder = Instance.new("Folder")
trailFolder.Name = "FirstJoinTrail"
trailFolder.Parent = workspace

local chevrons = {}
do
	for i = 1, CHEVRON_COUNT do
		local p = Instance.new("Part")
		p.Name = "Chevron" .. i
		p.Size = Vector3.new(3.2, 3.2, 3.2)
		p.Anchored = true
		p.CanCollide = false
		p.CanQuery = false
		p.CanTouch = false
		p.CastShadow = false
		p.Locked = true
		p.Material = Enum.Material.Neon
		p.Color = UITheme.Color.Sunny
		p.Transparency = 1
		-- Parented at the world origin would put eight glowing lumps in the middle of Forest for one
		-- frame; `RarityBeam`'s `scenery` note is about exactly this. Fully transparent from birth, so
		-- there is nothing to see until `updateTrail` has placed it.
		p.Parent = trailFolder

		local mesh = Instance.new("SpecialMesh")
		-- Guarded: `MeshType.Pyramid` was probed on this build, but this module is old enough to
		-- outlive a Studio version and a chevron that fails to become a pyramid should still be a
		-- glowing marker rather than an error that takes the whole guide down.
		local okMesh = pcall(function() mesh.MeshType = Enum.MeshType.Pyramid end)
		if not okMesh then
			mesh.MeshType = Enum.MeshType.Brick
		end
		mesh.Scale = Vector3.new(1, 1, 1)
		mesh.Parent = p

		chevrons[i] = p
	end
end

local function hideTrail()
	for _, p in ipairs(chevrons) do
		p.Transparency = 1
	end
end

-- `toPos` is where the player is being sent; nil switches the trail off. Called every tick from the
-- guide loop, so it does all its own no-op checks rather than making the caller branch.
local function updateTrail(toPos, tone)
	if trailSuspended or not toPos then
		hideTrail()
		return
	end
	local char = player.Character
	local root = char and char:FindFirstChild("HumanoidRootPart")
	if not root then
		hideTrail()
		return
	end

	local from = root.Position
	local flat = Vector3.new(toPos.X - from.X, 0, toPos.Z - from.Z)
	local dist = flat.Magnitude
	-- ARRIVED, or so close that a trail would be pointing through the player's own feet. Also the
	-- degenerate case: standing exactly on the target makes `flat.Unit` a NaN vector, which would
	-- write NaN CFrames and leave eight parts stuck at the origin until the next reparent.
	if dist < CHEVRON_ARRIVED then
		hideTrail()
		return
	end
	local dir = flat.Unit

	-- The pattern scrolls rather than the parts being re-spaced: each chevron's distance along the
	-- path is its index times the gap, plus a shared phase that advances with the clock and wraps at
	-- one gap. That is what makes it read as motion toward the target rather than as eight stationary
	-- markers -- and it costs one modulo instead of a per-part animation.
	local phase = (os.clock() * CHEVRON_SPEED) % CHEVRON_GAP
	for i, p in ipairs(chevrons) do
		local along = CHEVRON_START + (i - 1) * CHEVRON_GAP + phase
		if along >= dist - 2 then
			-- past the target: park it rather than drawing an arrow beyond the thing it points at
			p.Transparency = 1
		else
			local at = from + dir * along + Vector3.new(0, 3.4, 0)
			-- `CFrame.lookAt` puts -Z down the path and the pyramid's apex is +Y, so the mesh is
			-- tipped forward a quarter turn to make the point lead. Without the rotation every
			-- chevron is an arrow aimed at the sky.
			p.CFrame = CFrame.lookAt(at, at + dir) * CFrame.Angles(-math.pi / 2, 0, 0)
			-- Nearest is brightest and they fade with distance down the path, so the eye is pulled
			-- along the line in the direction of travel rather than seeing eight equal lumps.
			local fade = (i - 1) / CHEVRON_COUNT
			p.Transparency = 0.12 + fade * 0.55
			if tone then
				p.Color = tone
			end
		end
	end
end

-- `height` is how far above the target's own top the marker floats, so it clears a Swarmer and a
-- Guardian alike without being told how big either is.
local function pointAt(target, height)
	-- `trailSuspended` for the same reason `updateTrail` reads it, and this is the half that was
	-- missing. The panel watcher hides the guide by setting `gui.Enabled = false`, which governs
	-- GuiObjects -- and neither of these is one. A `BillboardGui` is its own LayerCollector and
	-- carries its own `Enabled`; a `Highlight` renders off its `Adornee` and does not care what it
	-- is parented to at all. So opening the Store left a creature outlined in yellow with a beacon
	-- bobbing over it, behind the panel the player had just opened.
	--
	-- Read HERE rather than in the watcher, because the guide loop calls `pointAt` every frame:
	-- anything the watcher switched off would be switched straight back on by the next tick.
	if trailSuspended or not target then
		marker.Enabled = false
		pointHL.Enabled = false
		pointHL.Adornee = nil
		marker.Adornee = nil
		return nil
	end
	local adornee = target
	if target:IsA("Model") then
		adornee = target.PrimaryPart or target:FindFirstChildWhichIsA("BasePart")
	end
	if not adornee then return nil end
	local _, size = pcall(function() return target:IsA("Model") and select(2, target:GetBoundingBox()) or target.Size end)
	local top = (typeof(size) == "Vector3" and size.Y or 6) * 0.5
	marker.Adornee = adornee
	-- 18.23: the marker BOBS, on its own sine rather than on a tween. A tween on a
	-- `StudsOffsetWorldSpace` would need one TweenService object per re-adorn, and this is re-adorned
	-- every frame onto a walking creature -- the arithmetic is free and cannot leak.
	marker.StudsOffsetWorldSpace = Vector3.new(0, top + (height or 5) + math.sin(os.clock() * 4) * 0.8, 0)
	marker.Enabled = true
	pointHL.Adornee = target
	pointHL.Enabled = true
	-- Handed back so the caller can feed the trail without resolving the target's position a second
	-- time -- the Model-vs-Part unwrap above is the fiddly half and doing it twice is how the two
	-- would drift apart.
	return adornee.Position
end

-- The nearest LIVE creature. Two traps, both already paid for elsewhere in this game and both silent
-- if ignored: `workspace.Creatures` holds loose `Part`s (`DeathBurst`) as well as rigs, so anything
-- that assumes a Model errors on a bare part; and a creature's health is a replicated ATTRIBUTE, not
-- a Humanoid -- asking for `Humanoid.Health` reports zero live creatures in a world holding hundreds,
-- which reads exactly like an empty street rather than like a wrong question.
local function nearestCreature()
	local char = player.Character
	local root = char and char:FindFirstChild("HumanoidRootPart")
	local folder = workspace:FindFirstChild("Creatures")
	if not root or not folder then return nil end
	local best, bestD = nil, 260
	for _, m in ipairs(folder:GetChildren()) do
		if m:IsA("Model") and (m:GetAttribute("Health") or 0) > 0 then
			local part = m.PrimaryPart
			if part then
				local d = (part.Position - root.Position).Magnitude
				if d < bestD then best, bestD = m, d end
			end
		end
	end
	return best
end

-- The nearest way UP. The flights live in `WorldShell` rather than in the zone folder, because
-- `TerraceRamp` is in ZoneBuilder's ALWAYS_LOADED set -- walkable ground that is allowed to stream
-- out is a hole to fall through. Looking for them in the zone finds nothing and looks exactly like
-- the ramps never having been built.
local function nearestRamp()
	local char = player.Character
	local root = char and char:FindFirstChild("HumanoidRootPart")
	local shell = workspace:FindFirstChild("WorldShell")
	if not root or not shell then return nil end
	local best, bestD = nil, 900
	for _, d in ipairs(shell:GetChildren()) do
		if d.Name == "TerraceRamp" then
			local dist = (d.Position - root.Position).Magnitude
			if dist < bestD then best, bestD = d, dist end
		end
	end
	return best
end

-- ============================================================================
-- WHAT THE PLAYER IS BEING ASKED TO DO
-- ============================================================================
-- Two steps, and which one is showing is derived from the save every tick rather than remembered.
-- A remembered step gets out of step with the world the first time something else moves the numbers
-- -- an offline payout, a code, a gift -- and then the guide is confidently wrong.
--
-- This is also the reason the plugin's model was not adopted wholesale. Tutorial Builder walks a
-- FIXED list with a "Next" button, which means the tutorial's idea of where you are and the save's
-- idea of where you are can disagree -- press Next twice and you are being told to evolve while the
-- server still says you cannot. Deriving it costs one function and cannot desynchronise.
local function stepFor(data)
	if not data then return nil end
	local step = GameConfig.GetEvolveStep(data)
	if step.isMax then return nil end
	-- XP alone, because XP alone is what the server checks now -- see DNAService.HandleEvolve. The
	-- DNA half of this test would have told a new player they were not ready while the button they
	-- are being pointed at was already green.
	if (data.XP or 0) >= step.xpCost then
		return "evolve"
	end
	return "fight"
end

-- Forward-declared: `runGuide` calls this and Lua binds an upvalue where a function is WRITTEN, so
-- without the name in scope here the call below would resolve to a nil global.
local runClimbBeat

local function runGuide()
	if state.running then return end
	state.running = true
	-- Repainted on every run rather than once at build time. The completion beat below repaints this
	-- card green and never puts it back, so a guide that ever restarts -- a player who quits
	-- mid-tutorial and returns in the same session -- would be given its instructions in the colour
	-- that means "finished". A one-way write to shared state is a bug waiting for a second caller.
	paintedKey = nil
	paintIfChanged("fight")

	task.spawn(function()
		local ok, err = pcall(function()
			local t0 = os.clock()
			while state.data and not state.data.TutorialDone do
				local which = stepFor(state.data)
				if which then
					banner.Visible = true
					paintIfChanged(which)
				else
					banner.Visible = false
				end

				-- the arrow belongs to the evolve step only: pointing at a button the player cannot
				-- press yet is an instruction to do something that will fail
				local btn = which == "evolve" and findEvolveButton() or nil
				if btn then
					local pos, size = btn.AbsolutePosition, btn.AbsoluteSize
					-- the bob runs along the axis it points down, so it reads as nudging the player
					-- toward the button rather than bouncing beside it
					local bob = math.abs(math.sin((os.clock() - t0) * 3.6)) * ARROW_BOB
					arrow.Position = UDim2.new(0, pos.X - 10 - bob, 0, pos.Y + size.Y * 0.5)
					arrow.Visible = true

					-- 18.23: the halo is re-fitted every frame from the same two live values, not
					-- placed once. The responsive pass at the bottom of MainUI resizes that button on
					-- any viewport change, and a ring sized at first sight would be left floating
					-- beside it -- worse than no ring, because it points at nothing.
					buttonHalo.Position = UDim2.new(0, pos.X - 4, 0, pos.Y - 4)
					buttonHalo.Size = UDim2.new(0, size.X + 8, 0, size.Y + 8)
					haloStroke.Transparency = 0.15 + 0.45 * math.abs(math.sin((os.clock() - t0) * 4))
					buttonHalo.Visible = true
				else
					arrow.Visible = false
					buttonHalo.Visible = false
				end

				-- AND THE OTHER HALF OF THE INSTRUCTION (9.10). "Click a creature" names the verb;
				-- the marker names the noun. Re-targeted every tick rather than locked on: the chosen
				-- creature is walking, can be killed by somebody else, and can stream out -- a guide
				-- pinned to one target ends up pointing at nothing and telling the player to hit it.
				--
				-- 18.22: and the trail is fed off the SAME resolved position, so the arrows on the
				-- ground and the marker in the air can never disagree about which creature is meant.
				if which == "fight" then
					local at = pointAt(nearestCreature(), 6)
					updateTrail(at, UITheme.Color.Sunny)
				else
					pointAt(nil)
					-- The evolve beat's target is a BUTTON, which is on the screen and not in the
					-- world: there is nowhere on the ground to send the player, so the trail stands
					-- down and the on-screen arrow carries that step alone.
					updateTrail(nil)
				end
				STEP:Wait()
			end
		end)

		banner.Visible = false
		arrow.Visible = false
		buttonHalo.Visible = false
		pointAt(nil)
		updateTrail(nil)
		state.running = false
		if not ok then
			warn("[FirstJoin] guide failed: " .. tostring(err))
		end

		-- The evolve itself is already celebrated by EvolveReveal's "New X Discovered!" card, so this
		-- adds one line rather than a second card: what to do NEXT, which is the one thing that card
		-- cannot say.
		if state.data and state.data.TutorialDone then
			-- FUNNEL STEP 6 (Phase 20). The guide is over: the evolve landed and this client got as
			-- far as showing the card that says so. Seconds after step 5 and deliberately so -- in
			-- this game the tutorial IS the first evolve, so the two steps are near-simultaneous by
			-- design and the interesting drop-off in this funnel is 4 -> 5, not 5 -> 6. The step is
			-- still worth having: it is the only one that proves a client reached the end of the
			-- sequence rather than the server having written the flag underneath it.
			pcall(function()
				local remotes = game:GetService("ReplicatedStorage"):FindFirstChild("Remotes")
				local step = remotes and remotes:FindFirstChild("TelemetryStep")
				if step then step:FireServer("tutorialDone") end
			end)
			paintIfChanged("done")
			banner.Visible = true
			task.delay(DONE_BANNER_TIME, function()
				banner.Visible = false
				runClimbBeat()
			end)
		end
	end)
end

-- ============================================================================
-- THE FOURTH BEAT: CLIMB (9.10)
-- ============================================================================
-- attack -> reward -> evolve are the first three and were already here. The row asks for a fourth,
-- and it is the one piece of this world nobody discovers on their own: the terraces carry the
-- stronger creatures and the shard drops, and the flights up them stand 400+ studs off the street.
-- A player who is never told looks at a valley and assumes that is the game.
--
-- SHOWN ONCE, AFTER THE EVOLVE, and driven by nothing that persists. There is no save field for it
-- and there should not be: a field means a migration and a repair for every existing save (6.3's
-- `TutorialDone` needed exactly that), for a banner that costs nothing if it is occasionally missed.
-- A session flag is the honest weight for a one-line hint.
--
-- 18.22: THIS IS THE BEAT THE TRAIL WAS BUILT FOR. A ramp is a fixed piece of geometry hundreds of
-- studs away and often behind the player -- the case where "look up there" is least useful and a
-- line of arrows on the ground is most. It is also why the trail is fed here on its own loop rather
-- than left adorned: the player is walking toward it, so the arrows have to be recomputed.
--
-- ===== BOTH GUARDS BELOW WERE DELETED BY THE 18.23 COMPACTION AND ARE RESTORED (19.6) =====
--
-- The `not ramp` one is the live defect. Without it this beat shows "Climb to the next terrace --
-- Tougher creatures, higher XP drops" for a full seven seconds WHEREVER the player happens to be,
-- and `pointAt(nil)` / `updateTrail(nil)` then correctly draw no marker and no trail -- so a player
-- in the arena or the Colosseum, neither of which has a terrace at all, is handed an instruction
-- with no target and no way to tell what it means. Saying nothing is the right answer when there is
-- no flight in range; pointing at the horizon is not.
--
-- The `climbShown` one is cheap insurance rather than an observed fault: today the only caller is
-- the `task.delay` in the completion branch above, and `onData` returns early once `TutorialDone`
-- is set, so it cannot currently fire twice. It is a one-shot hint and it should say so in its own
-- body rather than depend on that argument staying true.
runClimbBeat = function()
	if state.climbShown then return end
	state.climbShown = true
	local ramp = nearestRamp()
	-- No flight within range is a normal answer, not a failure: the arena and the Colosseum have
	-- no terraces at all. Say nothing rather than pointing at the horizon.
	if not ramp then return end
	paintIfChanged("climb")
	banner.Visible = true
	local t0 = os.clock()
	task.spawn(function()
		-- Re-resolved every tick rather than the single `ramp` above being reused: the player is
		-- walking toward it, the flights stream, and `pointAt` has to be called every frame anyway
		-- to survive the panel watcher (see its header). The lookup above is only the "is there one
		-- at all" question, which has to be answered before the banner is shown.
		while os.clock() - t0 < CLIMB_BEAT_TIME do
			local at = pointAt(nearestRamp(), 10)
			updateTrail(at, UITheme.Color.Aqua)
			STEP:Wait()
		end
		banner.Visible = false
		pointAt(nil)
		updateTrail(nil)
	end)
end

-- ============================================================================
-- WIRING
-- ============================================================================
local function onData(data)
	if type(data) ~= "table" then return end
	state.data = data
	if data.TutorialDone then return end

	if not state.panned then
		state.panned = true
		task.spawn(panCamera)
	end
	runGuide()
end

-- ONE SUBSCRIPTION, AND NOTHING TO ASK. There used to be a fallback here that invoked a
-- `GetData` RemoteFunction if the first `DataUpdate` was missed. There is no `GetData`, and no
-- `RemoteFunction` and no `OnServerInvoke` anywhere in this game -- the whole codebase is one-way
-- remotes plus a `StringValue` for anything a client needs to pull. So the fallback never ran;
-- what it did do was `WaitForChild("GetData", 10)` on the main thread, ten seconds of a brand-new
-- player's first minute spent waiting for something that was never going to be parented.
--
-- The race it was written for is real and is closed on the server instead, where it is closed for
-- every listener at once: `PlayerDataService` now pushes three times over the first ~1.5 s of a
-- join. See the comment on `PlayerAdded`.
Remotes:WaitForChild("DataUpdate").OnClientEvent:Connect(onData)
